TEST_F ( ExtensionServiceSyncTest , IgnoreSyncChangesWhenLocalStateIsMoreRecent ) {
 base : : FilePath source_install_dir = data_dir ( ) . AppendASCII ( "good" ) . AppendASCII ( "Extensions" ) ;
 base : : FilePath pref_path = source_install_dir . DirName ( ) . Append ( chrome : : kPreferencesFilename ) ;
 InitializeInstalledExtensionService ( pref_path , source_install_dir ) ;
 browser_sync : : ProfileSyncService * sync_service = ProfileSyncServiceFactory : : GetForProfile ( profile ( ) ) ;
 sync_service -> SetFirstSetupComplete ( ) ;
 extension_sync_service ( ) ;
 service ( ) -> Init ( ) ;
 ASSERT_TRUE ( service ( ) -> is_ready ( ) ) ;
 ASSERT_EQ ( 3u , loaded_ . size ( ) ) ;
 ASSERT_TRUE ( service ( ) -> IsExtensionEnabled ( good0 ) ) ;
 ASSERT_TRUE ( service ( ) -> IsExtensionEnabled ( good2 ) ) ;
 service ( ) -> DisableExtension ( good0 , extensions : : disable_reason : : DISABLE_USER_ACTION ) ;
 ASSERT_FALSE ( service ( ) -> IsExtensionEnabled ( good0 ) ) ;
 service ( ) -> EnableExtension ( good0 ) ;
 ASSERT_TRUE ( service ( ) -> IsExtensionEnabled ( good0 ) ) ;
 service ( ) -> DisableExtension ( good2 , extensions : : disable_reason : : DISABLE_USER_ACTION ) ;
 ASSERT_FALSE ( service ( ) -> IsExtensionEnabled ( good2 ) ) ;
 const Extension * extension0 = service ( ) -> GetExtensionById ( good0 , true ) ;
 const Extension * extension2 = service ( ) -> GetExtensionById ( good2 , true ) ;
 ASSERT_TRUE ( extensions : : sync_helper : : IsSyncable ( extension0 ) ) ;
 ASSERT_TRUE ( extensions : : sync_helper : : IsSyncable ( extension2 ) ) ;
 ExtensionSyncData disable_good0 ( * extension0 , false , extensions : : disable_reason : : DISABLE_USER_ACTION , false , false , ExtensionSyncData : : BOOLEAN_UNSET , false ) ;
 ExtensionSyncData enable_good2 ( * extension2 , true , extensions : : disable_reason : : DISABLE_NONE , false , false , ExtensionSyncData : : BOOLEAN_UNSET , false ) ;
 syncer : : SyncDataList sync_data ;
 sync_data . push_back ( disable_good0 . GetSyncData ( ) ) ;
 sync_data . push_back ( enable_good2 . GetSyncData ( ) ) ;
 extension_sync_service ( ) -> MergeDataAndStartSyncing ( syncer : : EXTENSIONS , sync_data , base : : MakeUnique < syncer : : FakeSyncChangeProcessor > ( ) , base : : MakeUnique < syncer : : SyncErrorFactoryMock > ( ) ) ;
 EXPECT_TRUE ( service ( ) -> IsExtensionEnabled ( good0 ) ) ;
 EXPECT_FALSE ( service ( ) -> IsExtensionEnabled ( good2 ) ) ;
 }