static void restore_layer_context ( VP8_COMP * cpi , const int layer ) {
 LAYER_CONTEXT * lc = & cpi -> layer_context [ layer ] ;
 cpi -> current_layer = layer ;
 cpi -> target_bandwidth = lc -> target_bandwidth ;
 cpi -> oxcf . target_bandwidth = lc -> target_bandwidth ;
 cpi -> oxcf . starting_buffer_level = lc -> starting_buffer_level ;
 cpi -> oxcf . optimal_buffer_level = lc -> optimal_buffer_level ;
 cpi -> oxcf . maximum_buffer_size = lc -> maximum_buffer_size ;
 cpi -> oxcf . starting_buffer_level_in_ms = lc -> starting_buffer_level_in_ms ;
 cpi -> oxcf . optimal_buffer_level_in_ms = lc -> optimal_buffer_level_in_ms ;
 cpi -> oxcf . maximum_buffer_size_in_ms = lc -> maximum_buffer_size_in_ms ;
 cpi -> buffer_level = lc -> buffer_level ;
 cpi -> bits_off_target = lc -> bits_off_target ;
 cpi -> total_actual_bits = lc -> total_actual_bits ;
 cpi -> active_worst_quality = lc -> active_worst_quality ;
 cpi -> active_best_quality = lc -> active_best_quality ;
 cpi -> ni_av_qi = lc -> ni_av_qi ;
 cpi -> ni_tot_qi = lc -> ni_tot_qi ;
 cpi -> ni_frames = lc -> ni_frames ;
 cpi -> avg_frame_qindex = lc -> avg_frame_qindex ;
 cpi -> rate_correction_factor = lc -> rate_correction_factor ;
 cpi -> key_frame_rate_correction_factor = lc -> key_frame_rate_correction_factor ;
 cpi -> gf_rate_correction_factor = lc -> gf_rate_correction_factor ;
 cpi -> mb . zbin_over_quant = lc -> zbin_over_quant ;
 cpi -> inter_frame_target = lc -> inter_frame_target ;
 cpi -> total_byte_count = lc -> total_byte_count ;
 cpi -> common . filter_level = lc -> filter_level ;
 cpi -> last_frame_percent_intra = lc -> last_frame_percent_intra ;
 memcpy ( cpi -> mb . count_mb_ref_frame_usage , lc -> count_mb_ref_frame_usage , sizeof ( cpi -> mb . count_mb_ref_frame_usage ) ) ;
 }