const char * SSL_alert_desc_string ( int value ) {
 const char * str ;
 switch ( value & 0xff ) {
 case SSL3_AD_CLOSE_NOTIFY : str = "CN" ;
 break ;
 case SSL3_AD_UNEXPECTED_MESSAGE : str = "UM" ;
 break ;
 case SSL3_AD_BAD_RECORD_MAC : str = "BM" ;
 break ;
 case SSL3_AD_DECOMPRESSION_FAILURE : str = "DF" ;
 break ;
 case SSL3_AD_HANDSHAKE_FAILURE : str = "HF" ;
 break ;
 case SSL3_AD_NO_CERTIFICATE : str = "NC" ;
 break ;
 case SSL3_AD_BAD_CERTIFICATE : str = "BC" ;
 break ;
 case SSL3_AD_UNSUPPORTED_CERTIFICATE : str = "UC" ;
 break ;
 case SSL3_AD_CERTIFICATE_REVOKED : str = "CR" ;
 break ;
 case SSL3_AD_CERTIFICATE_EXPIRED : str = "CE" ;
 break ;
 case SSL3_AD_CERTIFICATE_UNKNOWN : str = "CU" ;
 break ;
 case SSL3_AD_ILLEGAL_PARAMETER : str = "IP" ;
 break ;
 case TLS1_AD_DECRYPTION_FAILED : str = "DC" ;
 break ;
 case TLS1_AD_RECORD_OVERFLOW : str = "RO" ;
 break ;
 case TLS1_AD_UNKNOWN_CA : str = "CA" ;
 break ;
 case TLS1_AD_ACCESS_DENIED : str = "AD" ;
 break ;
 case TLS1_AD_DECODE_ERROR : str = "DE" ;
 break ;
 case TLS1_AD_DECRYPT_ERROR : str = "CY" ;
 break ;
 case TLS1_AD_EXPORT_RESTRICTION : str = "ER" ;
 break ;
 case TLS1_AD_PROTOCOL_VERSION : str = "PV" ;
 break ;
 case TLS1_AD_INSUFFICIENT_SECURITY : str = "IS" ;
 break ;
 case TLS1_AD_INTERNAL_ERROR : str = "IE" ;
 break ;
 case TLS1_AD_USER_CANCELLED : str = "US" ;
 break ;
 case TLS1_AD_NO_RENEGOTIATION : str = "NR" ;
 break ;
 case TLS1_AD_UNSUPPORTED_EXTENSION : str = "UE" ;
 break ;
 case TLS1_AD_CERTIFICATE_UNOBTAINABLE : str = "CO" ;
 break ;
 case TLS1_AD_UNRECOGNIZED_NAME : str = "UN" ;
 break ;
 case TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE : str = "BR" ;
 break ;
 case TLS1_AD_BAD_CERTIFICATE_HASH_VALUE : str = "BH" ;
 break ;
 case TLS1_AD_UNKNOWN_PSK_IDENTITY : str = "UP" ;
 break ;
 default : str = "UK" ;
 break ;
 }
 return ( str ) ;
 }