TEST ( IdlCompiler , ArrayTypes ) {
 base : : ListValue list ;
 list . AppendInteger ( 33 ) ;
 list . Append ( std : : make_unique < base : : ListValue > ( ) ) ;
 std : : unique_ptr < Function10 : : Params > f10_params = Function10 : : Params : : Create ( list ) ;
 ASSERT_TRUE ( f10_params != NULL ) ;
 EXPECT_EQ ( 33 , f10_params -> x ) ;
 EXPECT_TRUE ( f10_params -> y . empty ( ) ) ;
 list . Clear ( ) ;
 list . AppendInteger ( 33 ) ;
 std : : unique_ptr < base : : ListValue > sublist ( new base : : ListValue ) ;
 sublist -> AppendInteger ( 34 ) ;
 sublist -> AppendInteger ( 35 ) ;
 list . Append ( std : : move ( sublist ) ) ;
 f10_params = Function10 : : Params : : Create ( list ) ;
 ASSERT_TRUE ( f10_params != NULL ) ;
 EXPECT_EQ ( 33 , f10_params -> x ) ;
 ASSERT_EQ ( 2u , f10_params -> y . size ( ) ) ;
 EXPECT_EQ ( 34 , f10_params -> y [ 0 ] ) ;
 EXPECT_EQ ( 35 , f10_params -> y [ 1 ] ) ;
 list . Clear ( ) ;
 MyType1 a ;
 MyType1 b ;
 a . x = 5 ;
 b . x = 6 ;
 a . y = std : : string ( "foo" ) ;
 b . y = std : : string ( "bar" ) ;
 std : : unique_ptr < base : : ListValue > sublist2 ( new base : : ListValue ) ;
 sublist2 -> Append ( a . ToValue ( ) ) ;
 sublist2 -> Append ( b . ToValue ( ) ) ;
 list . Append ( std : : move ( sublist2 ) ) ;
 std : : unique_ptr < Function11 : : Params > f11_params = Function11 : : Params : : Create ( list ) ;
 ASSERT_TRUE ( f11_params != NULL ) ;
 ASSERT_EQ ( 2u , f11_params -> arg . size ( ) ) ;
 EXPECT_EQ ( 5 , f11_params -> arg [ 0 ] . x ) ;
 EXPECT_EQ ( "foo" , f11_params -> arg [ 0 ] . y ) ;
 EXPECT_EQ ( 6 , f11_params -> arg [ 1 ] . x ) ;
 EXPECT_EQ ( "bar" , f11_params -> arg [ 1 ] . y ) ;
 }