static void test_wl4284_1 ( ) {
 int rc ;
 MYSQL_ROW row ;
 MYSQL_RES * result ;
 DBUG_ENTER ( "test_wl4284_1" ) ;
 myheader ( "test_wl4284_1" ) ;
 rc = mysql_autocommit ( mysql , FALSE ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "DROP TABLE IF EXISTS trans" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "CREATE TABLE trans (a INT) ENGINE= InnoDB" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "INSERT INTO trans VALUES(1)" ) ;
 myquery ( rc ) ;
 rc = mysql_refresh ( mysql , REFRESH_GRANT | REFRESH_TABLES ) ;
 myquery ( rc ) ;
 rc = mysql_rollback ( mysql ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "SELECT * FROM trans" ) ;
 myquery ( rc ) ;
 result = mysql_use_result ( mysql ) ;
 mytest ( result ) ;
 row = mysql_fetch_row ( result ) ;
 mytest ( row ) ;
 mysql_free_result ( result ) ;
 rc = mysql_autocommit ( mysql , TRUE ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "DROP TABLE trans" ) ;
 myquery ( rc ) ;
 DBUG_VOID_RETURN ;
 }