void http_init ( ) {
 static int init = 1 ;
 if ( init ) {
 init = 0 ;
 mime_init ( ) ;
 url_init ( ) ;
 HTTP_METHOD_CONNECT = hdrtoken_string_to_wks ( "CONNECT" ) ;
 HTTP_METHOD_DELETE = hdrtoken_string_to_wks ( "DELETE" ) ;
 HTTP_METHOD_GET = hdrtoken_string_to_wks ( "GET" ) ;
 HTTP_METHOD_HEAD = hdrtoken_string_to_wks ( "HEAD" ) ;
 HTTP_METHOD_ICP_QUERY = hdrtoken_string_to_wks ( "ICP_QUERY" ) ;
 HTTP_METHOD_OPTIONS = hdrtoken_string_to_wks ( "OPTIONS" ) ;
 HTTP_METHOD_POST = hdrtoken_string_to_wks ( "POST" ) ;
 HTTP_METHOD_PURGE = hdrtoken_string_to_wks ( "PURGE" ) ;
 HTTP_METHOD_PUT = hdrtoken_string_to_wks ( "PUT" ) ;
 HTTP_METHOD_TRACE = hdrtoken_string_to_wks ( "TRACE" ) ;
 HTTP_METHOD_PUSH = hdrtoken_string_to_wks ( "PUSH" ) ;
 HTTP_WKSIDX_CONNECT = hdrtoken_wks_to_index ( HTTP_METHOD_CONNECT ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_DELETE = hdrtoken_wks_to_index ( HTTP_METHOD_DELETE ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_GET = hdrtoken_wks_to_index ( HTTP_METHOD_GET ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_HEAD = hdrtoken_wks_to_index ( HTTP_METHOD_HEAD ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_ICP_QUERY = hdrtoken_wks_to_index ( HTTP_METHOD_ICP_QUERY ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_OPTIONS = hdrtoken_wks_to_index ( HTTP_METHOD_OPTIONS ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_POST = hdrtoken_wks_to_index ( HTTP_METHOD_POST ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_PURGE = hdrtoken_wks_to_index ( HTTP_METHOD_PURGE ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_PUT = hdrtoken_wks_to_index ( HTTP_METHOD_PUT ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_TRACE = hdrtoken_wks_to_index ( HTTP_METHOD_TRACE ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_WKSIDX_PUSH = hdrtoken_wks_to_index ( HTTP_METHOD_PUSH ) ;
 HTTP_WKSIDX_METHODS_CNT ++ ;
 HTTP_LEN_CONNECT = hdrtoken_wks_to_length ( HTTP_METHOD_CONNECT ) ;
 HTTP_LEN_DELETE = hdrtoken_wks_to_length ( HTTP_METHOD_DELETE ) ;
 HTTP_LEN_GET = hdrtoken_wks_to_length ( HTTP_METHOD_GET ) ;
 HTTP_LEN_HEAD = hdrtoken_wks_to_length ( HTTP_METHOD_HEAD ) ;
 HTTP_LEN_ICP_QUERY = hdrtoken_wks_to_length ( HTTP_METHOD_ICP_QUERY ) ;
 HTTP_LEN_OPTIONS = hdrtoken_wks_to_length ( HTTP_METHOD_OPTIONS ) ;
 HTTP_LEN_POST = hdrtoken_wks_to_length ( HTTP_METHOD_POST ) ;
 HTTP_LEN_PURGE = hdrtoken_wks_to_length ( HTTP_METHOD_PURGE ) ;
 HTTP_LEN_PUT = hdrtoken_wks_to_length ( HTTP_METHOD_PUT ) ;
 HTTP_LEN_TRACE = hdrtoken_wks_to_length ( HTTP_METHOD_TRACE ) ;
 HTTP_LEN_PUSH = hdrtoken_wks_to_length ( HTTP_METHOD_PUSH ) ;
 HTTP_VALUE_BYTES = hdrtoken_string_to_wks ( "bytes" ) ;
 HTTP_VALUE_CHUNKED = hdrtoken_string_to_wks ( "chunked" ) ;
 HTTP_VALUE_CLOSE = hdrtoken_string_to_wks ( "close" ) ;
 HTTP_VALUE_COMPRESS = hdrtoken_string_to_wks ( "compress" ) ;
 HTTP_VALUE_DEFLATE = hdrtoken_string_to_wks ( "deflate" ) ;
 HTTP_VALUE_GZIP = hdrtoken_string_to_wks ( "gzip" ) ;
 HTTP_VALUE_IDENTITY = hdrtoken_string_to_wks ( "identity" ) ;
 HTTP_VALUE_KEEP_ALIVE = hdrtoken_string_to_wks ( "keep-alive" ) ;
 HTTP_VALUE_MAX_AGE = hdrtoken_string_to_wks ( "max-age" ) ;
 HTTP_VALUE_MAX_STALE = hdrtoken_string_to_wks ( "max-stale" ) ;
 HTTP_VALUE_MIN_FRESH = hdrtoken_string_to_wks ( "min-fresh" ) ;
 HTTP_VALUE_MUST_REVALIDATE = hdrtoken_string_to_wks ( "must-revalidate" ) ;
 HTTP_VALUE_NONE = hdrtoken_string_to_wks ( "none" ) ;
 HTTP_VALUE_NO_CACHE = hdrtoken_string_to_wks ( "no-cache" ) ;
 HTTP_VALUE_NO_STORE = hdrtoken_string_to_wks ( "no-store" ) ;
 HTTP_VALUE_NO_TRANSFORM = hdrtoken_string_to_wks ( "no-transform" ) ;
 HTTP_VALUE_ONLY_IF_CACHED = hdrtoken_string_to_wks ( "only-if-cached" ) ;
 HTTP_VALUE_PRIVATE = hdrtoken_string_to_wks ( "private" ) ;
 HTTP_VALUE_PROXY_REVALIDATE = hdrtoken_string_to_wks ( "proxy-revalidate" ) ;
 HTTP_VALUE_PUBLIC = hdrtoken_string_to_wks ( "public" ) ;
 HTTP_VALUE_S_MAXAGE = hdrtoken_string_to_wks ( "s-maxage" ) ;
 HTTP_VALUE_NEED_REVALIDATE_ONCE = hdrtoken_string_to_wks ( "need-revalidate-once" ) ;
 HTTP_VALUE_100_CONTINUE = hdrtoken_string_to_wks ( "100-continue" ) ;
 HTTP_LEN_BYTES = hdrtoken_wks_to_length ( HTTP_VALUE_BYTES ) ;
 HTTP_LEN_CHUNKED = hdrtoken_wks_to_length ( HTTP_VALUE_CHUNKED ) ;
 HTTP_LEN_CLOSE = hdrtoken_wks_to_length ( HTTP_VALUE_CLOSE ) ;
 HTTP_LEN_COMPRESS = hdrtoken_wks_to_length ( HTTP_VALUE_COMPRESS ) ;
 HTTP_LEN_DEFLATE = hdrtoken_wks_to_length ( HTTP_VALUE_DEFLATE ) ;
 HTTP_LEN_GZIP = hdrtoken_wks_to_length ( HTTP_VALUE_GZIP ) ;
 HTTP_LEN_IDENTITY = hdrtoken_wks_to_length ( HTTP_VALUE_IDENTITY ) ;
 HTTP_LEN_KEEP_ALIVE = hdrtoken_wks_to_length ( HTTP_VALUE_KEEP_ALIVE ) ;
 HTTP_LEN_MAX_AGE = hdrtoken_wks_to_length ( HTTP_VALUE_MAX_AGE ) ;
 HTTP_LEN_MAX_STALE = hdrtoken_wks_to_length ( HTTP_VALUE_MAX_STALE ) ;
 HTTP_LEN_MIN_FRESH = hdrtoken_wks_to_length ( HTTP_VALUE_MIN_FRESH ) ;
 HTTP_LEN_MUST_REVALIDATE = hdrtoken_wks_to_length ( HTTP_VALUE_MUST_REVALIDATE ) ;
 HTTP_LEN_NONE = hdrtoken_wks_to_length ( HTTP_VALUE_NONE ) ;
 HTTP_LEN_NO_CACHE = hdrtoken_wks_to_length ( HTTP_VALUE_NO_CACHE ) ;
 HTTP_LEN_NO_STORE = hdrtoken_wks_to_length ( HTTP_VALUE_NO_STORE ) ;
 HTTP_LEN_NO_TRANSFORM = hdrtoken_wks_to_length ( HTTP_VALUE_NO_TRANSFORM ) ;
 HTTP_LEN_ONLY_IF_CACHED = hdrtoken_wks_to_length ( HTTP_VALUE_ONLY_IF_CACHED ) ;
 HTTP_LEN_PRIVATE = hdrtoken_wks_to_length ( HTTP_VALUE_PRIVATE ) ;
 HTTP_LEN_PROXY_REVALIDATE = hdrtoken_wks_to_length ( HTTP_VALUE_PROXY_REVALIDATE ) ;
 HTTP_LEN_PUBLIC = hdrtoken_wks_to_length ( HTTP_VALUE_PUBLIC ) ;
 HTTP_LEN_S_MAXAGE = hdrtoken_wks_to_length ( HTTP_VALUE_S_MAXAGE ) ;
 HTTP_LEN_NEED_REVALIDATE_ONCE = hdrtoken_wks_to_length ( HTTP_VALUE_NEED_REVALIDATE_ONCE ) ;
 HTTP_LEN_100_CONTINUE = hdrtoken_wks_to_length ( HTTP_VALUE_100_CONTINUE ) ;

 i < ( int ) SIZEOF ( cache_control_values ) ;
 i ++ ) {
 cache_control_values [ i ] = hdrtoken_string_to_wks ( cache_control_names [ i ] ) ;
 }

 }