static void test_mysql_insert_id ( ) {
 my_ulonglong res ;
 int rc ;
 myheader ( "test_mysql_insert_id" ) ;
 rc = mysql_query ( mysql , "drop table if exists t1" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "create table t1 (f1 int, f2 varchar(255), key(f1))" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "insert into t1 values (1,'a')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "insert into t1 values (null,'b')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "insert into t1 select 5,'c'" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "create table t2 (f1 int not null primary key auto_increment, f2 varchar(255))" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,'b')" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "insert into t1 select 5,'c'" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "drop table t2" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "insert into t1 select null,'d'" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "insert into t1 values (null,last_insert_id(300))" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 300 ) ;
 rc = mysql_query ( mysql , "insert into t1 select null,last_insert_id(400)" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 400 ) ;
 rc = mysql_query ( mysql , "create table t2 (f1 int not null primary key auto_increment, f2 varchar(255))" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "insert into t2 values (1,'a')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 1 ) ;
 rc = mysql_query ( mysql , "insert into t1 values (10,'e')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,'b')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 2 ) ;
 rc = mysql_query ( mysql , "insert into t2 select 5,'c'" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 5 ) ;
 rc = mysql_query ( mysql , "insert into t2 select null,'d'" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 6 ) ;
 rc = mysql_query ( mysql , "insert into t2 values (10,'a'),(11,'b')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 11 ) ;
 rc = mysql_query ( mysql , "insert into t2 select 12,'a' union select 13,'b'" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 13 ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,'a'),(null,'b')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 14 ) ;
 rc = mysql_query ( mysql , "insert into t2 select null,'a' union select null,'b'" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 16 ) ;
 rc = mysql_query ( mysql , "insert into t2 select 12,'a' union select 13,'b'" ) ;
 myquery_r ( rc ) ;
 rc = mysql_query ( mysql , "insert ignore into t2 select 12,'a' union select 13,'b'" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "insert into t2 values (12,'a'),(13,'b')" ) ;
 myquery_r ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "insert ignore into t2 values (12,'a'),(13,'b')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,'e'),(12,'a'),(13,'b')" ) ;
 myquery_r ( rc ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,'e'),(12,'a'),(13,'b'),(25,'g')" ) ;
 myquery_r ( rc ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,last_insert_id(300))" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 20 ) ;
 rc = mysql_query ( mysql , "drop table t2" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "create table t2 (f1 int not null primary key " "auto_increment, f2 varchar(255), unique (f2))" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,'e')" ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 1 ) ;
 rc = mysql_query ( mysql , "insert ignore into t2 values (null,'e'),(null,'a'),(null,'e')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 2 ) ;
 rc = mysql_query ( mysql , "insert ignore into t2 values (null,'e'),(12,'c'),(null,'d')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 13 ) ;
 rc = mysql_query ( mysql , "update t2 set f1=14 where f1=12" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "update t2 set f1=0 where f1=14" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "update t2 set f2=last_insert_id(372) where f1=0" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 372 ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,'g')" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 15 ) ;
 rc = mysql_query ( mysql , "update t2 set f2=(@li:=last_insert_id()) where f1=15" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 0 ) ;
 rc = mysql_query ( mysql , "insert into t2 values (null,@li) on duplicate key " "update f2=concat('we updated ',f2)" ) ;
 myquery ( rc ) ;
 res = mysql_insert_id ( mysql ) ;
 DIE_UNLESS ( res == 15 ) ;
 rc = mysql_query ( mysql , "drop table t1,t2" ) ;
 myquery ( rc ) ;
 }