TEST_F ( ShortcutsProviderTest , TrickySingleMatch ) {
 base : : string16 text ( ASCIIToUTF16 ( "about:o" ) ) ;
 std : : string expected_url ( "chrome://omnibox/" ) ;
 ExpectedURLs expected_urls ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , true ) ) ;
 RunShortcutsProviderTest ( provider_ , text , false , expected_urls , expected_url , ASCIIToUTF16 ( "mnibox" ) ) ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , false ) ) ;
 RunShortcutsProviderTest ( provider_ , text , true , expected_urls , expected_url , ASCIIToUTF16 ( "mnibox" ) ) ;
 text = ASCIIToUTF16 ( "www/real sp" ) ;
 expected_url = "http://www/real%20space/long-url-with-space.html" ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , true ) ) ;
 RunShortcutsProviderTest ( provider_ , text , false , expected_urls , expected_url , ASCIIToUTF16 ( "ace/long-url-with-space.html" ) ) ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , false ) ) ;
 RunShortcutsProviderTest ( provider_ , text , true , expected_urls , expected_url , ASCIIToUTF16 ( "ace/long-url-with-space.html" ) ) ;
 text = ASCIIToUTF16 ( "notrailing.com/" ) ;
 expected_url = "http:/otrailing.com/" ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , true ) ) ;
 RunShortcutsProviderTest ( provider_ , text , true , expected_urls , expected_url , base : : string16 ( ) ) ;
 text = ASCIIToUTF16 ( "http:///foo.com" ) ;
 expected_url = "http://foo.com/" ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , true ) ) ;
 RunShortcutsProviderTest ( provider_ , text , true , expected_urls , expected_url , base : : string16 ( ) ) ;
 text = ASCIIToUTF16 ( "trailing1" ) ;
 expected_url = "http://trailing1.com/" ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , true ) ) ;
 RunShortcutsProviderTest ( provider_ , text , false , expected_urls , expected_url , ASCIIToUTF16 ( ".com" ) ) ;
 text = ASCIIToUTF16 ( "trailing1 " ) ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , false ) ) ;
 RunShortcutsProviderTest ( provider_ , text , false , expected_urls , expected_url , ASCIIToUTF16 ( ".com" ) ) ;
 text = ASCIIToUTF16 ( "about:trailing2" ) ;
 expected_url = "chrome://trailing2blah/" ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , true ) ) ;
 RunShortcutsProviderTest ( provider_ , text , false , expected_urls , expected_url , ASCIIToUTF16 ( "blah" ) ) ;
 text = ASCIIToUTF16 ( "about:trailing2 " ) ;
 expected_urls . clear ( ) ;
 expected_urls . push_back ( ExpectedURLAndAllowedToBeDefault ( expected_url , false ) ) ;
 RunShortcutsProviderTest ( provider_ , text , false , expected_urls , expected_url , ASCIIToUTF16 ( "blah" ) ) ;
 }