static void test_tran_bdb ( ) {
 MYSQL_RES * result ;
 MYSQL_ROW row ;
 int rc ;
 myheader ( "test_tran_bdb" ) ;
 rc = mysql_autocommit ( mysql , FALSE ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "DROP TABLE IF EXISTS my_demo_transaction" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "CREATE TABLE my_demo_transaction( " "col1 int , col2 varchar(30)) ENGINE= BDB" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "INSERT INTO my_demo_transaction VALUES(10, 'venu')" ) ;
 myquery ( rc ) ;
 rc = mysql_commit ( mysql ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "INSERT INTO my_demo_transaction VALUES(20, 'mysql')" ) ;
 myquery ( rc ) ;
 rc = mysql_rollback ( mysql ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "DELETE FROM my_demo_transaction WHERE col1= 10" ) ;
 myquery ( rc ) ;
 rc = mysql_rollback ( mysql ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "SELECT * FROM my_demo_transaction" ) ;
 myquery ( rc ) ;
 result = mysql_store_result ( mysql ) ;
 mytest ( result ) ;
 ( void ) my_process_result_set ( result ) ;
 mysql_free_result ( result ) ;
 rc = mysql_query ( mysql , "SELECT * FROM my_demo_transaction" ) ;
 myquery ( rc ) ;
 result = mysql_use_result ( mysql ) ;
 mytest ( result ) ;
 row = mysql_fetch_row ( result ) ;
 mytest ( row ) ;
 row = mysql_fetch_row ( result ) ;
 mytest_r ( row ) ;
 mysql_free_result ( result ) ;
 mysql_autocommit ( mysql , TRUE ) ;
 }