void dissect_zcl_color_control_attr_data ( proto_tree * tree , tvbuff_t * tvb , guint * offset , guint16 attr_id , guint data_type ) {
 static const int * capabilities_fields [ ] = {
 & hf_zbee_zcl_color_control_attr_color_capabilities_hs , & hf_zbee_zcl_color_control_attr_color_capabilities_ehs , & hf_zbee_zcl_color_control_attr_color_capabilities_loop , & hf_zbee_zcl_color_control_attr_color_capabilities_xy , & hf_zbee_zcl_color_control_attr_color_capabilities_ct , NULL }
 ;
 switch ( attr_id ) {
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_CURRENT_HUE : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_current_hue , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_CURRENT_SATURATION : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_current_saturation , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_REMAINING_TIME : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_remaining_time , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_CURRENT_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_CURRENT_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_DRIFT_COMPENSATION : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_drift_compensation , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_TEMP : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_temperature , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_MODE : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_mode , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_NO_OF_PRIMARIES : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_nr_of_primaries , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_1_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_1_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_1_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_1_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_1_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_1_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_2_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_2_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_2_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_2_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_2_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_2_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_3_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_3_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_3_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_3_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_3_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_3_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_4_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_4_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_4_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_4_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_4_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_4_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_5_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_5_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_5_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_5_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_5_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_5_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_6_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_6_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_6_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_6_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_PRIMARY_6_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_primary_6_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_WHITE_POINT_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_white_point_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_WHITE_POINT_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_white_point_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_R_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_red_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_R_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_red_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_R_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_red_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_G_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_green_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_G_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_green_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_G_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_green_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_B_X : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_blue_x , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_B_Y : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_blue_y , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_POINT_B_INTENSITY : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_blue_intensity , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_ENHANCED_CURRENT_HUE : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_enhanced_current_hue , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_ENHANCED_COLOR_MODE : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_enhanced_color_mode , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_LOOP_ACTIVE : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_loop_active , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_LOOP_DIRECTION : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_loop_direction , tvb , * offset , 1 , ENC_NA ) ;
 * offset += 1 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_LOOP_TIME : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_loop_time , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_LOOP_START_ENH_HUE : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_loop_start_enhanced_hue , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_LOOP_STORED_ENH_HUE : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_loop_stored_enhanced_hue , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_CAPABILITIES : proto_tree_add_bitmask ( tree , tvb , * offset , hf_zbee_zcl_color_control_attr_color_capabilities , ett_zbee_zcl_color_control_color_capabilities , capabilities_fields , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_TEMPERATURE_PHYS_MIN : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_temperature_phys_min , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COLOR_TEMPERATURE_PHYS_MAX : proto_tree_add_item ( tree , hf_zbee_zcl_color_control_attr_color_temperature_phys_max , tvb , * offset , 2 , ENC_LITTLE_ENDIAN ) ;
 * offset += 2 ;
 break ;
 case ZBEE_ZCL_ATTR_ID_COLOR_CONTROL_COMPENSATION_TEXT : default : dissect_zcl_attr_data ( tvb , tree , offset , data_type ) ;
 break ;
 }
 }