void gtkui_show_connections ( void ) {
 GtkWidget * scrolled , * vbox , * items , * hbox , * button , * tbox ;
 GtkWidget * context_menu , * frame , * entry , * chkb_tcp , * chkb_udp , * chkb_other ;
 GtkWidget * chkb_active , * chkb_idle , * chkb_closing , * chkb_closed , * chkb_killed ;
 GtkTreeModel * model ;
 GtkToolItem * toolbutton ;
 GtkCellRenderer * renderer ;
 GtkTreeViewColumn * column ;
 DEBUG_MSG ( "gtk_show_connections" ) ;
 if ( conns_window ) {
 if ( GTK_IS_WINDOW ( conns_window ) ) gtk_window_present ( GTK_WINDOW ( conns_window ) ) ;
 else gtkui_page_present ( conns_window ) ;
 return ;
 }
 conns_window = gtkui_page_new ( "Connections" , & gtkui_kill_connections , & gtkui_connections_detach ) ;
 vbox = gtkui_box_new ( GTK_ORIENTATION_VERTICAL , 0 , FALSE ) ;
 gtk_container_add ( GTK_CONTAINER ( conns_window ) , vbox ) ;
 gtk_widget_show ( vbox ) ;
 hbox = gtkui_box_new ( GTK_ORIENTATION_HORIZONTAL , 10 , FALSE ) ;
 gtk_box_pack_start ( GTK_BOX ( vbox ) , hbox , FALSE , FALSE , 0 ) ;
 frame = gtk_frame_new ( "Host filter" ) ;
 tbox = gtkui_box_new ( GTK_ORIENTATION_HORIZONTAL , 0 , FALSE ) ;
 gtk_container_add ( GTK_CONTAINER ( frame ) , tbox ) ;
 entry = gtk_entry_new ( ) ;
 g_signal_connect ( G_OBJECT ( entry ) , "activate" , G_CALLBACK ( set_connfilter_host ) , NULL ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , entry , FALSE , FALSE , 5 ) ;
 toolbutton = gtk_tool_button_new_from_stock ( GTK_STOCK_APPLY ) ;
 g_signal_connect_swapped ( G_OBJECT ( toolbutton ) , "clicked" , G_CALLBACK ( set_connfilter_host ) , entry ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , GTK_WIDGET ( toolbutton ) , FALSE , FALSE , 5 ) ;
 filter . host = NULL ;
 gtk_box_pack_start ( GTK_BOX ( hbox ) , frame , FALSE , FALSE , 0 ) ;
 frame = gtk_frame_new ( "Protocol filter" ) ;
 tbox = gtkui_box_new ( GTK_ORIENTATION_HORIZONTAL , 0 , FALSE ) ;
 gtk_container_add ( GTK_CONTAINER ( frame ) , tbox ) ;
 chkb_tcp = gtk_check_button_new_with_label ( "TCP" ) ;
 gtk_toggle_button_set_active ( GTK_TOGGLE_BUTTON ( chkb_tcp ) , TRUE ) ;
 filter . tcp = TRUE ;
 g_signal_connect ( G_OBJECT ( chkb_tcp ) , "toggled" , G_CALLBACK ( set_connfilter ) , & filter . tcp ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , chkb_tcp , FALSE , FALSE , 5 ) ;
 chkb_udp = gtk_check_button_new_with_label ( "UDP" ) ;
 gtk_toggle_button_set_active ( GTK_TOGGLE_BUTTON ( chkb_udp ) , TRUE ) ;
 filter . udp = TRUE ;
 g_signal_connect ( G_OBJECT ( chkb_udp ) , "toggled" , G_CALLBACK ( set_connfilter ) , & filter . udp ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , chkb_udp , FALSE , FALSE , 5 ) ;
 chkb_other = gtk_check_button_new_with_label ( "Other" ) ;
 gtk_toggle_button_set_active ( GTK_TOGGLE_BUTTON ( chkb_other ) , TRUE ) ;
 filter . other = TRUE ;
 g_signal_connect ( G_OBJECT ( chkb_other ) , "toggled" , G_CALLBACK ( set_connfilter ) , & filter . other ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , chkb_other , FALSE , FALSE , 5 ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox ) , frame , FALSE , FALSE , 0 ) ;
 frame = gtk_frame_new ( "Connection state filter" ) ;
 tbox = gtkui_box_new ( GTK_ORIENTATION_HORIZONTAL , 0 , FALSE ) ;
 gtk_container_add ( GTK_CONTAINER ( frame ) , tbox ) ;
 chkb_active = gtk_check_button_new_with_label ( "Active" ) ;
 gtk_toggle_button_set_active ( GTK_TOGGLE_BUTTON ( chkb_active ) , TRUE ) ;
 filter . active = TRUE ;
 g_signal_connect ( G_OBJECT ( chkb_active ) , "toggled" , G_CALLBACK ( set_connfilter ) , & filter . active ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , chkb_active , FALSE , FALSE , 5 ) ;
 chkb_idle = gtk_check_button_new_with_label ( "Idle" ) ;
 gtk_toggle_button_set_active ( GTK_TOGGLE_BUTTON ( chkb_idle ) , TRUE ) ;
 filter . idle = TRUE ;
 g_signal_connect ( G_OBJECT ( chkb_idle ) , "toggled" , G_CALLBACK ( set_connfilter ) , & filter . idle ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , chkb_idle , FALSE , FALSE , 5 ) ;
 chkb_closing = gtk_check_button_new_with_label ( "Closing" ) ;
 gtk_toggle_button_set_active ( GTK_TOGGLE_BUTTON ( chkb_closing ) , TRUE ) ;
 filter . closing = TRUE ;
 g_signal_connect ( G_OBJECT ( chkb_closing ) , "toggled" , G_CALLBACK ( set_connfilter ) , & filter . closing ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , chkb_closing , FALSE , FALSE , 5 ) ;
 chkb_closed = gtk_check_button_new_with_label ( "Closed" ) ;
 gtk_toggle_button_set_active ( GTK_TOGGLE_BUTTON ( chkb_closed ) , TRUE ) ;
 filter . closed = TRUE ;
 g_signal_connect ( G_OBJECT ( chkb_closed ) , "toggled" , G_CALLBACK ( set_connfilter ) , & filter . closed ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , chkb_closed , FALSE , FALSE , 5 ) ;
 chkb_killed = gtk_check_button_new_with_label ( "Killed" ) ;
 gtk_toggle_button_set_active ( GTK_TOGGLE_BUTTON ( chkb_killed ) , TRUE ) ;
 filter . killed = TRUE ;
 g_signal_connect ( G_OBJECT ( chkb_killed ) , "toggled" , G_CALLBACK ( set_connfilter ) , & filter . killed ) ;
 gtk_box_pack_start ( GTK_BOX ( tbox ) , chkb_killed , FALSE , FALSE , 5 ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox ) , frame , FALSE , FALSE , 0 ) ;
 gtk_widget_show_all ( hbox ) ;
 scrolled = gtk_scrolled_window_new ( NULL , NULL ) ;
 gtk_scrolled_window_set_policy ( GTK_SCROLLED_WINDOW ( scrolled ) , GTK_POLICY_AUTOMATIC , GTK_POLICY_AUTOMATIC ) ;
 gtk_scrolled_window_set_shadow_type ( GTK_SCROLLED_WINDOW ( scrolled ) , GTK_SHADOW_IN ) ;
 gtk_box_pack_start ( GTK_BOX ( vbox ) , scrolled , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( scrolled ) ;
 treeview = gtk_tree_view_new ( ) ;
 gtk_container_add ( GTK_CONTAINER ( scrolled ) , treeview ) ;
 gtk_widget_show ( treeview ) ;
 selection = gtk_tree_view_get_selection ( GTK_TREE_VIEW ( treeview ) ) ;
 gtk_tree_selection_set_mode ( selection , GTK_SELECTION_SINGLE ) ;
 g_signal_connect ( G_OBJECT ( treeview ) , "row_activated" , G_CALLBACK ( gtkui_connection_data ) , NULL ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( " " , renderer , "text" , 0 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 0 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "Host " , renderer , "text" , 1 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 1 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "Port" , renderer , "text" , 2 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 2 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "-" , renderer , "text" , 3 , NULL ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "Host " , renderer , "text" , 4 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 4 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "Port" , renderer , "text" , 5 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 5 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "Proto" , renderer , "text" , 6 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 6 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "State" , renderer , "text" , 7 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 7 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "TX Bytes" , renderer , "text" , 8 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 8 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;
 renderer = gtk_cell_renderer_text_new ( ) ;
 column = gtk_tree_view_column_new_with_attributes ( "RX Bytes" , renderer , "text" , 9 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 9 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;

 column = gtk_tree_view_column_new_with_attributes ( "Countries" , renderer , "text" , 10 , NULL ) ;
 gtk_tree_view_column_set_sort_column_id ( column , 10 ) ;
 gtk_tree_view_append_column ( GTK_TREE_VIEW ( treeview ) , column ) ;

 gtk_box_pack_start ( GTK_BOX ( vbox ) , hbox , FALSE , FALSE , 0 ) ;
 gtk_widget_show ( hbox ) ;
 button = gtk_button_new_with_mnemonic ( "View _Details" ) ;
 g_signal_connect ( G_OBJECT ( button ) , "clicked" , G_CALLBACK ( gtkui_connection_detail ) , NULL ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox ) , button , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( button ) ;
 button = gtk_button_new_with_mnemonic ( "_Kill Connection" ) ;
 g_signal_connect ( G_OBJECT ( button ) , "clicked" , G_CALLBACK ( gtkui_connection_kill ) , NULL ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox ) , button , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( button ) ;
 button = gtk_button_new_with_mnemonic ( "E_xpunge Connections" ) ;
 g_signal_connect ( G_OBJECT ( button ) , "clicked" , G_CALLBACK ( gtkui_connection_purge ) , NULL ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox ) , button , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( button ) ;
 context_menu = gtk_menu_new ( ) ;
 items = gtk_menu_item_new_with_label ( "View Details" ) ;
 gtk_menu_shell_append ( GTK_MENU_SHELL ( context_menu ) , items ) ;
 g_signal_connect ( G_OBJECT ( items ) , "activate" , G_CALLBACK ( gtkui_connection_detail ) , NULL ) ;
 gtk_widget_show ( items ) ;
 items = gtk_menu_item_new_with_label ( "Kill Connection" ) ;
 gtk_menu_shell_append ( GTK_MENU_SHELL ( context_menu ) , items ) ;
 g_signal_connect ( G_OBJECT ( items ) , "activate" , G_CALLBACK ( gtkui_connection_kill ) , NULL ) ;
 gtk_widget_show ( items ) ;
 g_signal_connect ( G_OBJECT ( treeview ) , "button-press-event" , G_CALLBACK ( gtkui_context_menu ) , context_menu ) ;
 refresh_connections ( NULL ) ;
 filter . model = gtk_tree_model_filter_new ( GTK_TREE_MODEL ( ls_conns ) , NULL ) ;
 gtk_tree_model_filter_set_visible_func ( GTK_TREE_MODEL_FILTER ( filter . model ) , ( GtkTreeModelFilterVisibleFunc ) connfilter , NULL , NULL ) ;
 model = gtk_tree_model_sort_new_with_model ( filter . model ) ;
 gtk_tree_view_set_model ( GTK_TREE_VIEW ( treeview ) , model ) ;
 connections_idle = g_timeout_add ( 1000 , refresh_connections , NULL ) ;
 gtk_widget_show ( conns_window ) ;
 }