const char * http_hdr_reason_lookup ( unsigned status ) {

 HTTP_STATUS_ENTRY ( 0 , None ) ;
 HTTP_STATUS_ENTRY ( 100 , Continue ) ;
 HTTP_STATUS_ENTRY ( 101 , Switching Protocols ) ;
 HTTP_STATUS_ENTRY ( 102 , Processing ) ;
 HTTP_STATUS_ENTRY ( 103 , Early Hints ) ;
 HTTP_STATUS_ENTRY ( 200 , OK ) ;
 HTTP_STATUS_ENTRY ( 201 , Created ) ;
 HTTP_STATUS_ENTRY ( 202 , Accepted ) ;
 HTTP_STATUS_ENTRY ( 203 , Non - Authoritative Information ) ;
 HTTP_STATUS_ENTRY ( 204 , No Content ) ;
 HTTP_STATUS_ENTRY ( 205 , Reset Content ) ;
 HTTP_STATUS_ENTRY ( 206 , Partial Content ) ;
 HTTP_STATUS_ENTRY ( 207 , Multi - Status ) ;
 HTTP_STATUS_ENTRY ( 208 , Already Reported ) ;
 HTTP_STATUS_ENTRY ( 226 , IM Used ) ;
 HTTP_STATUS_ENTRY ( 300 , Multiple Choices ) ;
 HTTP_STATUS_ENTRY ( 301 , Moved Permanently ) ;
 HTTP_STATUS_ENTRY ( 302 , Found ) ;
 HTTP_STATUS_ENTRY ( 303 , See Other ) ;
 HTTP_STATUS_ENTRY ( 304 , Not Modified ) ;
 HTTP_STATUS_ENTRY ( 305 , Use Proxy ) ;
 HTTP_STATUS_ENTRY ( 307 , Temporary Redirect ) ;
 HTTP_STATUS_ENTRY ( 308 , Permanent Redirect ) ;
 HTTP_STATUS_ENTRY ( 400 , Bad Request ) ;
 HTTP_STATUS_ENTRY ( 401 , Unauthorized ) ;
 HTTP_STATUS_ENTRY ( 402 , Payment Required ) ;
 HTTP_STATUS_ENTRY ( 403 , Forbidden ) ;
 HTTP_STATUS_ENTRY ( 404 , Not Found ) ;
 HTTP_STATUS_ENTRY ( 405 , Method Not Allowed ) ;
 HTTP_STATUS_ENTRY ( 406 , Not Acceptable ) ;
 HTTP_STATUS_ENTRY ( 407 , Proxy Authentication Required ) ;
 HTTP_STATUS_ENTRY ( 408 , Request Timeout ) ;
 HTTP_STATUS_ENTRY ( 409 , Conflict ) ;
 HTTP_STATUS_ENTRY ( 410 , Gone ) ;
 HTTP_STATUS_ENTRY ( 411 , Length Required ) ;
 HTTP_STATUS_ENTRY ( 412 , Precondition Failed ) ;
 HTTP_STATUS_ENTRY ( 413 , Request Entity Too Large ) ;
 HTTP_STATUS_ENTRY ( 414 , Request - URI Too Long ) ;
 HTTP_STATUS_ENTRY ( 415 , Unsupported Media Type ) ;
 HTTP_STATUS_ENTRY ( 416 , Requested Range Not Satisfiable ) ;
 HTTP_STATUS_ENTRY ( 417 , Expectation Failed ) ;
 HTTP_STATUS_ENTRY ( 422 , Unprocessable Entity ) ;
 HTTP_STATUS_ENTRY ( 423 , Locked ) ;
 HTTP_STATUS_ENTRY ( 424 , Failed Dependency ) ;
 HTTP_STATUS_ENTRY ( 426 , Upgrade Required ) ;
 HTTP_STATUS_ENTRY ( 428 , Precondition Required ) ;
 HTTP_STATUS_ENTRY ( 429 , Too Many Requests ) ;
 HTTP_STATUS_ENTRY ( 431 , Request Header Fields Too Large ) ;
 HTTP_STATUS_ENTRY ( 500 , Internal Server Error ) ;
 HTTP_STATUS_ENTRY ( 501 , Not Implemented ) ;
 HTTP_STATUS_ENTRY ( 502 , Bad Gateway ) ;
 HTTP_STATUS_ENTRY ( 503 , Service Unavailable ) ;
 HTTP_STATUS_ENTRY ( 504 , Gateway Timeout ) ;
 HTTP_STATUS_ENTRY ( 505 , HTTP Version Not Supported ) ;
 HTTP_STATUS_ENTRY ( 506 , Variant Also Negotiates ) ;
 HTTP_STATUS_ENTRY ( 507 , Insufficient Storage ) ;
 HTTP_STATUS_ENTRY ( 508 , Loop Detected ) ;
 HTTP_STATUS_ENTRY ( 510 , Not Extended ) ;
 HTTP_STATUS_ENTRY ( 511 , Network Authentication Required ) ;
 }

 }