TEST ( ExtensionCSPValidator , EffectiveSandboxedPageCSP ) {
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "" ) , "child-src 'self';
 script-src 'self' 'unsafe-inline' 'unsafe-eval';
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "child-src http://www.google.com" ) , "child-src 'self';
 script-src 'self' 'unsafe-inline' 'unsafe-eval';
" , InsecureValueWarning ( "child-src" , "http://www.google.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "child-src *" ) , "child-src 'self';
 script-src 'self' 'unsafe-inline' 'unsafe-eval';
" , InsecureValueWarning ( "child-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "child-src 'none'" ) , "child-src 'none';
 script-src 'self' 'unsafe-inline' 'unsafe-eval';
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "script-src 'none';
 frame-src 'self';
" ) , "frame-src 'self';
 script-src 'none';
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "script-src 'none';
 frame-src 'self' http://www.google.com;
" ) , "frame-src 'self';
 script-src 'none';
" , InsecureValueWarning ( "frame-src" , "http://www.google.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "script-src 'self'" ) , "script-src 'self';
 child-src 'self'" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "script-src 'self' 'unsafe-inline';
 child-src 'self';
" ) , "child-src 'self';
 script-src 'self' 'unsafe-inline';
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "script-src 'self' 'unsafe-eval';
 child-src 'self';
" ) , "child-src 'self';
 script-src 'self' 'unsafe-eval';
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "script-src 'none';
 frame-src 'self' http://www.google.com;
" ) , "frame-src 'self';
 script-src 'none';
" , InsecureValueWarning ( "frame-src" , "http://www.google.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "script-src 'none';
 child-src 'self' http://www.google.com;
" ) , "child-src 'self';
 script-src 'none';
" , InsecureValueWarning ( "child-src" , "http://www.google.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeSandboxPageCSP ( "script-src 'none';
 child-src http://bar.com 'self' http://foo.com;
" ) , "child-src 'self';
 script-src 'none';
" , InsecureValueWarning ( "child-src" , "http://bar.com" ) , InsecureValueWarning ( "child-src" , "http://foo.com" ) ) ) ;
 }