TEST_F ( ShortcutsProviderTest , ClassifyAllMatchesInString ) {
 ACMatchClassifications matches = AutocompleteMatch : : ClassificationsFromString ( "0,0" ) ;
 ClassifyTest classify_test ( ASCIIToUTF16 ( "A man, a plan, a canal Panama" ) , matches ) ;
 ACMatchClassifications spans_a = classify_test . RunTest ( ASCIIToUTF16 ( "man" ) ) ;
 EXPECT_EQ ( "0,0,2,2,5,0" , AutocompleteMatch : : ClassificationsToString ( spans_a ) ) ;
 ACMatchClassifications spans_b = classify_test . RunTest ( ASCIIToUTF16 ( "man p" ) ) ;
 EXPECT_EQ ( "0,0,2,2,5,0,9,2,10,0,23,2,24,0" , AutocompleteMatch : : ClassificationsToString ( spans_b ) ) ;
 ACMatchClassifications spans_c = classify_test . RunTest ( ASCIIToUTF16 ( "man plan panama" ) ) ;
 EXPECT_EQ ( "0,0,2,2,5,0,9,2,13,0,23,2" , AutocompleteMatch : : ClassificationsToString ( spans_c ) ) ;
 ClassifyTest classify_test2 ( ASCIIToUTF16 ( "Yahoo! Sports - Sports News, " "Scores, Rumors, Fantasy Games, and more" ) , matches ) ;
 ACMatchClassifications spans_d = classify_test2 . RunTest ( ASCIIToUTF16 ( "ne" ) ) ;
 EXPECT_EQ ( "0,0,23,2,25,0" , AutocompleteMatch : : ClassificationsToString ( spans_d ) ) ;
 ACMatchClassifications spans_e = classify_test2 . RunTest ( ASCIIToUTF16 ( "news r" ) ) ;
 EXPECT_EQ ( "0,0,10,2,11,0,19,2,20,0,23,2,27,0,32,2,33,0,37,2,38,0,41,2,42,0," "66,2,67,0" , AutocompleteMatch : : ClassificationsToString ( spans_e ) ) ;
 matches = AutocompleteMatch : : ClassificationsFromString ( "0,1" ) ;
 ClassifyTest classify_test3 ( ASCIIToUTF16 ( "livescore.goal.com" ) , matches ) ;
 ACMatchClassifications spans_f = classify_test3 . RunTest ( ASCIIToUTF16 ( "go" ) ) ;
 EXPECT_EQ ( "0,1,10,3,12,1" , AutocompleteMatch : : ClassificationsToString ( spans_f ) ) ;
 matches = AutocompleteMatch : : ClassificationsFromString ( "0,0,13,1" ) ;
 ClassifyTest classify_test4 ( ASCIIToUTF16 ( "Email login: mail.somecorp.com" ) , matches ) ;
 ACMatchClassifications spans_g = classify_test4 . RunTest ( ASCIIToUTF16 ( "ail" ) ) ;
 EXPECT_EQ ( "0,0,2,2,5,0,13,1,14,3,17,1" , AutocompleteMatch : : ClassificationsToString ( spans_g ) ) ;
 ACMatchClassifications spans_h = classify_test4 . RunTest ( ASCIIToUTF16 ( "lo log" ) ) ;
 EXPECT_EQ ( "0,0,6,2,9,0,13,1" , AutocompleteMatch : : ClassificationsToString ( spans_h ) ) ;
 ACMatchClassifications spans_i = classify_test4 . RunTest ( ASCIIToUTF16 ( "ail em" ) ) ;
 EXPECT_EQ ( "0,2,5,0,13,1,14,3,17,1" , AutocompleteMatch : : ClassificationsToString ( spans_i ) ) ;
 class ClassifyTest classify_test5 ( ( base : : string16 ( ) ) , ACMatchClassifications ( ) ) ;
 ACMatchClassifications spans_j = classify_test5 . RunTest ( ASCIIToUTF16 ( "man" ) ) ;
 ASSERT_EQ ( 0U , spans_j . size ( ) ) ;
 matches = AutocompleteMatch : : ClassificationsFromString ( "0,4,9,0" ) ;
 ClassifyTest classify_test6 ( ASCIIToUTF16 ( "html password example" ) , matches ) ;
 ACMatchClassifications spans_k = classify_test6 . RunTest ( ASCIIToUTF16 ( "html pass" ) ) ;
 EXPECT_EQ ( "0,6,4,4,5,6,9,0" , AutocompleteMatch : : ClassificationsToString ( spans_k ) ) ;
 matches = AutocompleteMatch : : ClassificationsFromString ( "0,1,11,0" ) ;
 ClassifyTest classify_test7 ( ASCIIToUTF16 ( "http://a.co is great" ) , matches ) ;
 ACMatchClassifications spans_l = classify_test7 . RunTest ( ASCIIToUTF16 ( "ht co" ) ) ;
 EXPECT_EQ ( "0,3,2,1,9,3,11,0" , AutocompleteMatch : : ClassificationsToString ( spans_l ) ) ;
 }