TEST_F ( ScoredHistoryMatchTest , FilterMatches ) {
 WordStarts terms_to_word_starts_offsets ;
 terms_to_word_starts_offsets . push_back ( 0 ) ;
 WordStarts word_starts ;
 word_starts . push_back ( 0 ) ;
 word_starts . push_back ( 7 ) ;
 word_starts . push_back ( 12 ) ;
 word_starts . push_back ( 16 ) ;
 word_starts . push_back ( 24 ) ;
 word_starts . push_back ( 28 ) ;
 word_starts . push_back ( 37 ) ;
 word_starts . push_back ( 43 ) ;
 TermMatches term_matches ;
 term_matches . push_back ( TermMatch ( 0 , 0 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 32 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 37 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 43 , 1 ) ) ;
 TermMatches filtered_term_matches = ScoredHistoryMatch : : FilterTermMatchesByWordStarts ( term_matches , terms_to_word_starts_offsets , word_starts , 15 , std : : string : : npos ) ;
 ASSERT_EQ ( 3u , filtered_term_matches . size ( ) ) ;
 EXPECT_EQ ( 0u , filtered_term_matches [ 0 ] . offset ) ;
 EXPECT_EQ ( 37u , filtered_term_matches [ 1 ] . offset ) ;
 EXPECT_EQ ( 43u , filtered_term_matches [ 2 ] . offset ) ;
 filtered_term_matches = ScoredHistoryMatch : : FilterTermMatchesByWordStarts ( filtered_term_matches , terms_to_word_starts_offsets , word_starts , 0 , 5 ) ;
 ASSERT_EQ ( 3u , filtered_term_matches . size ( ) ) ;
 EXPECT_EQ ( 0u , filtered_term_matches [ 0 ] . offset ) ;
 EXPECT_EQ ( 37u , filtered_term_matches [ 1 ] . offset ) ;
 EXPECT_EQ ( 43u , filtered_term_matches [ 2 ] . offset ) ;
 term_matches . clear ( ) ;
 term_matches . push_back ( TermMatch ( 0 , 1 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 2 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 7 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 10 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 22 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 45 , 1 ) ) ;
 filtered_term_matches = ScoredHistoryMatch : : FilterTermMatchesByWordStarts ( term_matches , terms_to_word_starts_offsets , word_starts , 15 , std : : string : : npos ) ;
 ASSERT_EQ ( 4u , filtered_term_matches . size ( ) ) ;
 EXPECT_EQ ( 1u , filtered_term_matches [ 0 ] . offset ) ;
 EXPECT_EQ ( 2u , filtered_term_matches [ 1 ] . offset ) ;
 EXPECT_EQ ( 7u , filtered_term_matches [ 2 ] . offset ) ;
 EXPECT_EQ ( 10u , filtered_term_matches [ 3 ] . offset ) ;
 filtered_term_matches = ScoredHistoryMatch : : FilterTermMatchesByWordStarts ( filtered_term_matches , terms_to_word_starts_offsets , word_starts , 0 , 4 ) ;
 ASSERT_EQ ( 2u , filtered_term_matches . size ( ) ) ;
 EXPECT_EQ ( 7u , filtered_term_matches [ 0 ] . offset ) ;
 EXPECT_EQ ( 10u , filtered_term_matches [ 1 ] . offset ) ;
 term_matches . clear ( ) ;
 term_matches . push_back ( TermMatch ( 0 , 8 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 17 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 38 , 1 ) ) ;
 filtered_term_matches = ScoredHistoryMatch : : FilterTermMatchesByWordStarts ( term_matches , terms_to_word_starts_offsets , word_starts , 15 , std : : string : : npos ) ;
 ASSERT_EQ ( 1u , filtered_term_matches . size ( ) ) ;
 EXPECT_EQ ( 8u , filtered_term_matches [ 0 ] . offset ) ;
 term_matches . clear ( ) ;
 term_matches . push_back ( TermMatch ( 0 , 16 , 1 ) ) ;
 filtered_term_matches = ScoredHistoryMatch : : FilterTermMatchesByWordStarts ( term_matches , terms_to_word_starts_offsets , word_starts , 15 , std : : string : : npos ) ;
 ASSERT_EQ ( 1u , filtered_term_matches . size ( ) ) ;
 EXPECT_EQ ( 16u , filtered_term_matches [ 0 ] . offset ) ;
 term_matches . clear ( ) ;
 term_matches . push_back ( TermMatch ( 0 , 19 , 1 ) ) ;
 term_matches . push_back ( TermMatch ( 0 , 28 , 1 ) ) ;
 filtered_term_matches = ScoredHistoryMatch : : FilterTermMatchesByWordStarts ( term_matches , terms_to_word_starts_offsets , word_starts , 15 , std : : string : : npos ) ;
 ASSERT_EQ ( 1u , filtered_term_matches . size ( ) ) ;
 EXPECT_EQ ( 28u , filtered_term_matches [ 0 ] . offset ) ;
 terms_to_word_starts_offsets [ 0 ] = 1 ;
 term_matches . clear ( ) ;
 term_matches . push_back ( TermMatch ( 0 , 27 , 1 ) ) ;
 filtered_term_matches = ScoredHistoryMatch : : FilterTermMatchesByWordStarts ( term_matches , terms_to_word_starts_offsets , word_starts , 15 , std : : string : : npos ) ;
 ASSERT_EQ ( 1u , filtered_term_matches . size ( ) ) ;
 EXPECT_EQ ( 27u , filtered_term_matches [ 0 ] . offset ) ;
 }