TEST_F ( PrintPreviewUIUnitTest , GetCurrentPrintPreviewStatus ) {
 WebContents * initiator = browser ( ) -> tab_strip_model ( ) -> GetActiveWebContents ( ) ;
 ASSERT_TRUE ( initiator ) ;
 printing : : PrintPreviewDialogController * controller = printing : : PrintPreviewDialogController : : GetInstance ( ) ;
 ASSERT_TRUE ( controller ) ;
 printing : : PrintViewManager * print_view_manager = printing : : PrintViewManager : : FromWebContents ( initiator ) ;
 print_view_manager -> PrintPreviewNow ( initiator -> GetMainFrame ( ) , false ) ;
 WebContents * preview_dialog = controller -> GetOrCreatePreviewDialog ( initiator ) ;
 EXPECT_NE ( initiator , preview_dialog ) ;
 EXPECT_EQ ( 1 , browser ( ) -> tab_strip_model ( ) -> count ( ) ) ;
 EXPECT_TRUE ( IsShowingWebContentsModalDialog ( initiator ) ) ;
 PrintPreviewUI * preview_ui = static_cast < PrintPreviewUI * > ( preview_dialog -> GetWebUI ( ) -> GetController ( ) ) ;
 ASSERT_TRUE ( preview_ui != NULL ) ;
 bool cancel = false ;
 const int32_t kInvalidId = - 5 ;
 preview_ui -> GetCurrentPrintPreviewStatus ( kInvalidId , 0 , & cancel ) ;
 EXPECT_TRUE ( cancel ) ;
 const int kFirstRequestId = 1000 ;
 const int kSecondRequestId = 1001 ;
 const int32_t preview_ui_addr = preview_ui -> GetIDForPrintPreviewUI ( ) ;
 preview_ui -> OnPrintPreviewRequest ( kFirstRequestId ) ;
 cancel = true ;
 preview_ui -> GetCurrentPrintPreviewStatus ( preview_ui_addr , kFirstRequestId , & cancel ) ;
 EXPECT_FALSE ( cancel ) ;
 cancel = false ;
 preview_ui -> GetCurrentPrintPreviewStatus ( preview_ui_addr , kSecondRequestId , & cancel ) ;
 EXPECT_TRUE ( cancel ) ;
 preview_ui -> OnPrintPreviewRequest ( kSecondRequestId ) ;
 cancel = false ;
 preview_ui -> GetCurrentPrintPreviewStatus ( preview_ui_addr , kFirstRequestId , & cancel ) ;
 EXPECT_TRUE ( cancel ) ;
 cancel = true ;
 preview_ui -> GetCurrentPrintPreviewStatus ( preview_ui_addr , kSecondRequestId , & cancel ) ;
 EXPECT_FALSE ( cancel ) ;
 }