TEST_F ( HistoryQuickProviderTest , Spans ) {
 TermMatches matches_a ;
 matches_a . push_back ( TermMatch ( 1 , 1 , 2 ) ) ;
 matches_a . push_back ( TermMatch ( 2 , 4 , 3 ) ) ;
 matches_a . push_back ( TermMatch ( 3 , 9 , 1 ) ) ;
 matches_a . push_back ( TermMatch ( 3 , 10 , 1 ) ) ;
 matches_a . push_back ( TermMatch ( 4 , 14 , 5 ) ) ;
 ACMatchClassifications spans_a = HistoryQuickProvider : : SpansFromTermMatch ( matches_a , 20 , false ) ;
 ASSERT_EQ ( 9U , spans_a . size ( ) ) ;
 EXPECT_EQ ( 0U , spans_a [ 0 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : NONE , spans_a [ 0 ] . style ) ;
 EXPECT_EQ ( 1U , spans_a [ 1 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : MATCH , spans_a [ 1 ] . style ) ;
 EXPECT_EQ ( 3U , spans_a [ 2 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : NONE , spans_a [ 2 ] . style ) ;
 EXPECT_EQ ( 4U , spans_a [ 3 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : MATCH , spans_a [ 3 ] . style ) ;
 EXPECT_EQ ( 7U , spans_a [ 4 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : NONE , spans_a [ 4 ] . style ) ;
 EXPECT_EQ ( 9U , spans_a [ 5 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : MATCH , spans_a [ 5 ] . style ) ;
 EXPECT_EQ ( 11U , spans_a [ 6 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : NONE , spans_a [ 6 ] . style ) ;
 EXPECT_EQ ( 14U , spans_a [ 7 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : MATCH , spans_a [ 7 ] . style ) ;
 EXPECT_EQ ( 19U , spans_a [ 8 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : NONE , spans_a [ 8 ] . style ) ;
 TermMatches matches_b ;
 matches_b . push_back ( TermMatch ( 1 , 0 , 2 ) ) ;
 matches_b . push_back ( TermMatch ( 2 , 3 , 2 ) ) ;
 ACMatchClassifications spans_b = HistoryQuickProvider : : SpansFromTermMatch ( matches_b , 5 , true ) ;
 ASSERT_EQ ( 3U , spans_b . size ( ) ) ;
 EXPECT_EQ ( 0U , spans_b [ 0 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : MATCH | ACMatchClassification : : URL , spans_b [ 0 ] . style ) ;
 EXPECT_EQ ( 2U , spans_b [ 1 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : URL , spans_b [ 1 ] . style ) ;
 EXPECT_EQ ( 3U , spans_b [ 2 ] . offset ) ;
 EXPECT_EQ ( ACMatchClassification : : MATCH | ACMatchClassification : : URL , spans_b [ 2 ] . style ) ;
 }