static int dissct_rsl_msg ( tvbuff_t * tvb , packet_info * pinfo , proto_tree * tree , int offset ) {
 guint8 msg_disc , msg_type , sys_info_type ;
 msg_disc = tvb_get_guint8 ( tvb , offset ++ ) >> 1 ;
 msg_type = tvb_get_guint8 ( tvb , offset ) & 0x7f ;
 proto_tree_add_item ( tree , hf_rsl_msg_type , tvb , offset , 1 , ENC_BIG_ENDIAN ) ;
 if ( msg_disc == RSL_MSGDISC_IPACCESS ) {
 offset = dissct_rsl_ipaccess_msg ( tvb , pinfo , tree , offset ) ;
 return offset ;
 }
 offset ++ ;
 switch ( msg_type ) {
 case RSL_MSG_TYPE_DATA_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , TRUE , L3_INF_OTHER ) ;
 break ;
 case RSL_MSG_TYPE_DATA_IND : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , TRUE , L3_INF_OTHER ) ;
 break ;
 case RSL_MSG_TYPE_ERROR_IND : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_rlm_cause ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_TYPE_EST_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_TYPE_EST_CONF : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_EST_IND : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 1 ) offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , FALSE , L3_INF_OTHER ) ;
 break ;
 case RSL_MSG_REL_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_rel_mode ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_REL_CONF : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_REL_IND : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_UNIT_DATA_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , FALSE , L3_INF_OTHER ) ;
 break ;
 case RSL_MSG_BCCH_INFO : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_sys_info_type ( tvb , pinfo , tree , offset , TRUE , & sys_info_type ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_full_bcch_inf ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_starting_time ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_CCCH_LOAD_IND : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_rach_load ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_paging_load ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_CHANRQD : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_req_ref ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_access_delay ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_phy_ctx ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_DELETE_IND : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_full_imm_ass_inf ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_PAGING_CMD : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_paging_grp ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_ms_id ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ch_needed ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_emlpp_prio ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_IMM_ASS_CMD : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_full_imm_ass_inf ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_SMS_BC_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_smscb_inf ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_smscb_ch_ind ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_RF_RES_IND : offset = dissect_rsl_ie_resource_inf ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_SACCH_FILL : offset = dissect_rsl_ie_sys_info_type ( tvb , pinfo , tree , offset , TRUE , & sys_info_type ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , FALSE , ( sys_info_type == 0x48 ) ? L3_INF_SACCH : L3_INF_OTHER ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_starting_time ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_OVERLOAD : offset = dissect_rsl_ie_cause ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_ERROR_REPORT : offset = dissect_rsl_ie_cause ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_message_id ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_err_msg ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_SMS_BC_CMD : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_cb_cmd_type ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_smscb_mess ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_smscb_ch_ind ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_CBCH_LOAD_IND : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_cbch_load_inf ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_smscb_ch_ind ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_NOT_CMD : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_cmd_ind ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_grp_call_ref ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ch_desc ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_nch_drx ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_CHAN_ACTIV : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_act_type ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_ch_mode ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ch_id ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_enc_inf ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ho_ref ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_bs_power ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ms_pow ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_timing_adv ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_phy_ctx ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_uic ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_main_ch_ref ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_multirate_conf ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_multirate_cntrl ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_sup_codec_types ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_tfo_transp_cont ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_CHAN_ACTIV_ACK : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_frame_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_CHAN_ACTIV_N_ACK : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_cause ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_CONN_FAIL : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_cause ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_DEACTIVATE_SACCH : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_ENCR_CMD : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_enc_inf ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_link_id ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , TRUE , L3_INF_OTHER ) ;
 break ;
 case RSL_MSG_HANDODET : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_access_delay ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_MEAS_RES : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_meas_res_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_uplik_meas ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_bs_power ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_l1_inf ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) {
 if ( ( tvb_get_guint8 ( tvb , offset + 3 ) & 0xFE ) == 0x10 ) {
 offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , FALSE , L3_INF_SACCH ) ;
 }
 else {
 offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , FALSE , L3_INF_OTHER ) ;
 }
 }
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ms_timing_offset ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_MODE_MODIFY_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_ch_mode ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_enc_inf ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_main_ch_ref ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_multirate_conf ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_multirate_cntrl ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_sup_codec_types ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_tfo_transp_cont ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_MODE_MODIFY_ACK : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_MODE_MODIFY_NACK : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_cause ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_PHY_CONTEXT_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_PHY_CONTEXT_CONF : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_bs_power ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_ms_pow ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_timing_adv ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_phy_ctx ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_RF_CHAN_REL : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_MS_POWER_CONTROL : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ms_pow ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_BS_POWER_CONTROL : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_bs_power ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_PREPROC_CONFIG : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_PREPROC_MEAS_RES : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_RF_CHAN_REL_ACK : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_SACCH_INFO_MODIFY : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_sys_info_type ( tvb , pinfo , tree , offset , TRUE , & sys_info_type ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_L3_inf ( tvb , pinfo , tree , offset , FALSE , ( sys_info_type == 0x48 ) ? L3_INF_SACCH : L3_INF_OTHER ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_starting_time ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_TALKER_DET : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_LISTENER_DET : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_REMOTE_CODEC_CONF_REP : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_codec_conf ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_sup_codec_types ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_tfo_transp_cont ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_R_T_D_REP : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_rtd ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_PRE_HANDO_NOTIF : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_multirate_cntrl ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_codec_conf ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_tfo_transp_cont ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_MR_CODEC_MOD_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_multirate_conf ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_MR_CODEC_MOD_ACK : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_multirate_conf ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_MR_CODEC_MOD_NACK : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_cause ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_MR_CODEC_MOD_PER : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_multirate_conf ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_TFO_REP : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_tfo_status ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_TFO_MOD_REQ : offset = dissect_rsl_ie_ch_no ( tvb , pinfo , tree , offset , TRUE ) ;
 offset = dissect_rsl_ie_multirate_cntrl ( tvb , pinfo , tree , offset , TRUE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_sup_codec_types ( tvb , pinfo , tree , offset , FALSE ) ;
 if ( tvb_reported_length_remaining ( tvb , offset ) > 0 ) offset = dissect_rsl_ie_tfo_transp_cont ( tvb , pinfo , tree , offset , FALSE ) ;
 break ;
 case RSL_MSG_LOC_INF : offset = dissect_rsl_ie_llp_apdu ( tvb , pinfo , tree , offset , TRUE ) ;
 break ;
 case RSL_MSG_TYPE_IPAC_MEAS_PP_DEF : case RSL_MSG_TYPE_IPAC_HO_CAND_INQ : case RSL_MSG_TYPE_IPAC_HO_CAND_RESP : case RSL_MSG_TYPE_IPAC_PDCH_ACT : case RSL_MSG_TYPE_IPAC_PDCH_ACT_ACK : case RSL_MSG_TYPE_IPAC_PDCH_ACT_NACK : case RSL_MSG_TYPE_IPAC_PDCH_DEACT : case RSL_MSG_TYPE_IPAC_PDCH_DEACT_ACK : case RSL_MSG_TYPE_IPAC_PDCH_DEACT_NACK : if ( global_rsl_use_nano_bts ) offset = dissct_rsl_ipaccess_msg ( tvb , pinfo , tree , offset - 1 ) ;
 default : break ;
 }
 return offset ;
 }