TEST ( AutocompleteMatchTest , MergeClassifications ) {
 EXPECT_EQ ( std : : string ( ) , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ACMatchClassifications ( ) , AutocompleteMatch : : ACMatchClassifications ( ) ) ) ) ;
 EXPECT_EQ ( "0,0" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ClassificationsFromString ( "0,0" ) , AutocompleteMatch : : ACMatchClassifications ( ) ) ) ) ;
 EXPECT_EQ ( "0,0" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ACMatchClassifications ( ) , AutocompleteMatch : : ClassificationsFromString ( "0,0" ) ) ) ) ;
 EXPECT_EQ ( "0,1" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ClassificationsFromString ( "0,1" ) , AutocompleteMatch : : ACMatchClassifications ( ) ) ) ) ;
 EXPECT_EQ ( "0,1" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ACMatchClassifications ( ) , AutocompleteMatch : : ClassificationsFromString ( "0,1" ) ) ) ) ;
 EXPECT_EQ ( "0,1" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ClassificationsFromString ( "0,0" ) , AutocompleteMatch : : ClassificationsFromString ( "0,1" ) ) ) ) ;
 EXPECT_EQ ( "0,3," "1,2" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ClassificationsFromString ( "0,1," "1,0" ) , AutocompleteMatch : : ClassificationsFromString ( "0,2" ) ) ) ) ;
 EXPECT_EQ ( "0,3," "1,2" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ClassificationsFromString ( "0,2" ) , AutocompleteMatch : : ClassificationsFromString ( "0,1," "1,0" ) ) ) ) ;
 EXPECT_EQ ( "0,3" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ClassificationsFromString ( "0,1," "1,2" ) , AutocompleteMatch : : ClassificationsFromString ( "0,2," "1,1" ) ) ) ) ;
 EXPECT_EQ ( "0,2," "1,0," "2,1," "4,3," "5,7," "6,3," "7,7," "15,1," "17,0" , AutocompleteMatch : : ClassificationsToString ( AutocompleteMatch : : MergeClassifications ( AutocompleteMatch : : ClassificationsFromString ( "0,0," "2,1," "4,3," "7,7," "10,6," "15,0" ) , AutocompleteMatch : : ClassificationsFromString ( "0,2," "1,0," "5,7," "6,1," "17,0" ) ) ) ) ;
 }