static void test_bug31669 ( ) {
 int rc ;
 static char buff [ LARGE_BUFFER_SIZE + 1 ] ;

 static char db [ NAME_CHAR_LEN + 1 ] ;
 static char query [ LARGE_BUFFER_SIZE * 2 ] ;

 DBUG_ENTER ( "test_bug31669" ) ;
 myheader ( "test_bug31669" ) ;
 l_mysql = mysql_client_init ( NULL ) ;
 DIE_UNLESS ( l_mysql != NULL ) ;
 l_mysql = mysql_real_connect ( l_mysql , opt_host , opt_user , opt_password , current_db , opt_port , opt_unix_socket , 0 ) ;
 DIE_UNLESS ( l_mysql != 0 ) ;
 rc = mysql_change_user ( l_mysql , NULL , NULL , NULL ) ;
 DIE_UNLESS ( rc ) ;
 reconnect ( & l_mysql ) ;
 rc = mysql_change_user ( l_mysql , "" , "" , "" ) ;
 DIE_UNLESS ( rc ) ;
 reconnect ( & l_mysql ) ;
 memset ( buff , 'a' , sizeof ( buff ) ) ;
 buff [ sizeof ( buff ) - 1 ] = '\0' ;
 rc = mysql_change_user ( l_mysql , buff , buff , buff ) ;
 DIE_UNLESS ( rc ) ;
 reconnect ( & l_mysql ) ;
 rc = mysql_change_user ( mysql , opt_user , opt_password , current_db ) ;
 DIE_UNLESS ( ! rc ) ;

 db [ NAME_CHAR_LEN ] = 0 ;
 strxmov ( query , "CREATE DATABASE IF NOT EXISTS " , db , NullS ) ;
 rc = mysql_query ( mysql , query ) ;
 myquery ( rc ) ;
 memset ( user , 'b' , sizeof ( user ) ) ;
 user [ USERNAME_CHAR_LENGTH ] = 0 ;
 memset ( buff , 'c' , sizeof ( buff ) ) ;
 buff [ LARGE_BUFFER_SIZE ] = 0 ;
 strxmov ( query , "GRANT ALL PRIVILEGES ON *.* TO '" , user , "'@'%' IDENTIFIED BY " "'" , buff , "' WITH GRANT OPTION" , NullS ) ;
 rc = mysql_query ( mysql , query ) ;
 myquery ( rc ) ;
 strxmov ( query , "GRANT ALL PRIVILEGES ON *.* TO '" , user , "'@'localhost' IDENTIFIED BY " "'" , buff , "' WITH GRANT OPTION" , NullS ) ;
 rc = mysql_query ( mysql , query ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "FLUSH PRIVILEGES" ) ;
 myquery ( rc ) ;
 rc = mysql_change_user ( l_mysql , user , buff , db ) ;
 DIE_UNLESS ( ! rc ) ;
 user [ USERNAME_CHAR_LENGTH - 1 ] = 'a' ;
 rc = mysql_change_user ( l_mysql , user , buff , db ) ;
 DIE_UNLESS ( rc ) ;
 reconnect ( & l_mysql ) ;
 user [ USERNAME_CHAR_LENGTH - 1 ] = 'b' ;
 buff [ LARGE_BUFFER_SIZE - 1 ] = 'd' ;
 rc = mysql_change_user ( l_mysql , user , buff , db ) ;
 DIE_UNLESS ( rc ) ;
 reconnect ( & l_mysql ) ;
 buff [ LARGE_BUFFER_SIZE - 1 ] = 'c' ;
 db [ NAME_CHAR_LEN - 1 ] = 'e' ;
 rc = mysql_change_user ( l_mysql , user , buff , db ) ;
 DIE_UNLESS ( rc ) ;
 reconnect ( & l_mysql ) ;
 db [ NAME_CHAR_LEN - 1 ] = 'a' ;
 rc = mysql_change_user ( l_mysql , user , buff , db ) ;
 DIE_UNLESS ( ! rc ) ;
 rc = mysql_change_user ( l_mysql , user + 1 , buff + 1 , db + 1 ) ;
 DIE_UNLESS ( rc ) ;
 reconnect ( & l_mysql ) ;
 rc = mysql_change_user ( mysql , opt_user , opt_password , current_db ) ;
 DIE_UNLESS ( ! rc ) ;
 strxmov ( query , "DROP DATABASE " , db , NullS ) ;
 rc = mysql_query ( mysql , query ) ;
 myquery ( rc ) ;
 strxmov ( query , "DELETE FROM mysql.user WHERE User='" , user , "'" , NullS ) ;
 rc = mysql_query ( mysql , query ) ;
 myquery ( rc ) ;
 DIE_UNLESS ( mysql_affected_rows ( mysql ) == 2 ) ;
 mysql_close ( l_mysql ) ;

 }