static void gtkui_connection_data_split ( void ) {
 GtkWidget * vbox , * scrolled , * label , * child ;
 GtkWidget * hbox_big , * hbox_small , * button ;
 GtkTextIter iter ;
 char tmp [ MAX_ASCII_ADDR_LEN ] ;
 char title [ MAX_ASCII_ADDR_LEN + 6 ] ;
 static gint scroll_split = 1 ;
 DEBUG_MSG ( "gtk_connection_data_split" ) ;
 conntrack_hook_conn_del ( curr_conn , join_print_po ) ;
 if ( data_window ) {
 child = gtk_bin_get_child ( GTK_BIN ( data_window ) ) ;
 gtk_container_remove ( GTK_CONTAINER ( data_window ) , child ) ;
 textview3 = NULL ;
 joinedbuf = NULL ;
 endmark3 = NULL ;
 }
 else {
 data_window = gtkui_page_new ( "Connection data" , & gtkui_destroy_conndata , & gtkui_connection_data_detach ) ;
 }
 curr_conn -> flags |= CONN_VIEWING ;
 hbox_big = gtkui_box_new ( GTK_ORIENTATION_HORIZONTAL , 5 , TRUE ) ;
 gtk_container_add ( GTK_CONTAINER ( data_window ) , hbox_big ) ;
 gtk_widget_show ( hbox_big ) ;
 vbox = gtkui_box_new ( GTK_ORIENTATION_VERTICAL , 0 , FALSE ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox_big ) , vbox , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( vbox ) ;
 snprintf ( title , MAX_ASCII_ADDR_LEN + 6 , "%s:%d" , ip_addr_ntoa ( & curr_conn -> L3_addr1 , tmp ) , ntohs ( curr_conn -> L4_addr1 ) ) ;
 label = gtk_label_new ( title ) ;
 gtk_misc_set_alignment ( GTK_MISC ( label ) , 0 , 0.5 ) ;
 gtk_box_pack_start ( GTK_BOX ( vbox ) , label , FALSE , FALSE , 0 ) ;
 gtk_widget_show ( label ) ;
 scrolled = gtk_scrolled_window_new ( NULL , NULL ) ;
 gtk_scrolled_window_set_policy ( GTK_SCROLLED_WINDOW ( scrolled ) , GTK_POLICY_AUTOMATIC , GTK_POLICY_AUTOMATIC ) ;
 gtk_scrolled_window_set_shadow_type ( GTK_SCROLLED_WINDOW ( scrolled ) , GTK_SHADOW_IN ) ;
 gtk_box_pack_start ( GTK_BOX ( vbox ) , scrolled , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( scrolled ) ;
 textview1 = gtk_text_view_new ( ) ;
 gtk_text_view_set_wrap_mode ( GTK_TEXT_VIEW ( textview1 ) , GTK_WRAP_CHAR ) ;
 gtk_text_view_set_editable ( GTK_TEXT_VIEW ( textview1 ) , FALSE ) ;
 gtk_text_view_set_cursor_visible ( GTK_TEXT_VIEW ( textview1 ) , FALSE ) ;
 gtk_text_view_set_right_margin ( GTK_TEXT_VIEW ( textview1 ) , 5 ) ;
 gtk_text_view_set_right_margin ( GTK_TEXT_VIEW ( textview1 ) , 5 ) ;
 gtk_container_add ( GTK_CONTAINER ( scrolled ) , textview1 ) ;
 gtk_widget_show ( textview1 ) ;
 splitbuf1 = gtk_text_view_get_buffer ( GTK_TEXT_VIEW ( textview1 ) ) ;
 gtk_text_buffer_create_tag ( splitbuf1 , "blue_fg" , "foreground" , "blue" , NULL ) ;
 gtk_text_buffer_create_tag ( splitbuf1 , "monospace" , "family" , "monospace" , NULL ) ;
 gtk_text_buffer_get_end_iter ( splitbuf1 , & iter ) ;
 endmark1 = gtk_text_buffer_create_mark ( splitbuf1 , "end" , & iter , FALSE ) ;
 hbox_small = gtkui_box_new ( GTK_ORIENTATION_HORIZONTAL , 5 , TRUE ) ;
 gtk_box_pack_start ( GTK_BOX ( vbox ) , hbox_small , FALSE , FALSE , 0 ) ;
 gtk_widget_show ( hbox_small ) ;
 button = gtk_button_new_with_mnemonic ( "_Join Views" ) ;
 g_signal_connect ( G_OBJECT ( button ) , "clicked" , G_CALLBACK ( gtkui_connection_data_join ) , NULL ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox_small ) , button , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( button ) ;
 button = gtk_button_new_with_mnemonic ( "_Inject Data" ) ;
 g_signal_connect ( G_OBJECT ( button ) , "clicked" , G_CALLBACK ( gtkui_connection_inject ) , NULL ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox_small ) , button , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( button ) ;
 vbox = gtkui_box_new ( GTK_ORIENTATION_VERTICAL , 0 , FALSE ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox_big ) , vbox , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( vbox ) ;
 snprintf ( title , MAX_ASCII_ADDR_LEN + 6 , "%s:%d" , ip_addr_ntoa ( & curr_conn -> L3_addr2 , tmp ) , ntohs ( curr_conn -> L4_addr2 ) ) ;
 label = gtk_label_new ( title ) ;
 gtk_misc_set_alignment ( GTK_MISC ( label ) , 0 , 0.5 ) ;
 gtk_box_pack_start ( GTK_BOX ( vbox ) , label , FALSE , FALSE , 0 ) ;
 gtk_widget_show ( label ) ;
 scrolled = gtk_scrolled_window_new ( NULL , NULL ) ;
 gtk_scrolled_window_set_policy ( GTK_SCROLLED_WINDOW ( scrolled ) , GTK_POLICY_AUTOMATIC , GTK_POLICY_AUTOMATIC ) ;
 gtk_scrolled_window_set_shadow_type ( GTK_SCROLLED_WINDOW ( scrolled ) , GTK_SHADOW_IN ) ;
 gtk_box_pack_start ( GTK_BOX ( vbox ) , scrolled , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( scrolled ) ;
 textview2 = gtk_text_view_new ( ) ;
 gtk_text_view_set_wrap_mode ( GTK_TEXT_VIEW ( textview2 ) , GTK_WRAP_CHAR ) ;
 gtk_text_view_set_editable ( GTK_TEXT_VIEW ( textview2 ) , FALSE ) ;
 gtk_text_view_set_cursor_visible ( GTK_TEXT_VIEW ( textview2 ) , FALSE ) ;
 gtk_text_view_set_right_margin ( GTK_TEXT_VIEW ( textview2 ) , 5 ) ;
 gtk_text_view_set_right_margin ( GTK_TEXT_VIEW ( textview2 ) , 5 ) ;
 gtk_container_add ( GTK_CONTAINER ( scrolled ) , textview2 ) ;
 gtk_widget_show ( textview2 ) ;
 splitbuf2 = gtk_text_view_get_buffer ( GTK_TEXT_VIEW ( textview2 ) ) ;
 gtk_text_buffer_create_tag ( splitbuf2 , "blue_fg" , "foreground" , "blue" , NULL ) ;
 gtk_text_buffer_create_tag ( splitbuf2 , "monospace" , "family" , "monospace" , NULL ) ;
 gtk_text_buffer_get_end_iter ( splitbuf2 , & iter ) ;
 endmark2 = gtk_text_buffer_create_mark ( splitbuf2 , "end" , & iter , FALSE ) ;
 hbox_small = gtkui_box_new ( GTK_ORIENTATION_HORIZONTAL , 5 , TRUE ) ;
 gtk_box_pack_start ( GTK_BOX ( vbox ) , hbox_small , FALSE , FALSE , 0 ) ;
 gtk_widget_show ( hbox_small ) ;
 button = gtk_button_new_with_mnemonic ( "Inject _File" ) ;
 g_signal_connect ( G_OBJECT ( button ) , "clicked" , G_CALLBACK ( gtkui_connection_inject_file ) , NULL ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox_small ) , button , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( button ) ;
 button = gtk_button_new_with_mnemonic ( "_Kill Connection" ) ;
 g_signal_connect ( G_OBJECT ( button ) , "clicked" , G_CALLBACK ( gtkui_connection_kill_curr_conn ) , NULL ) ;
 gtk_box_pack_start ( GTK_BOX ( hbox_small ) , button , TRUE , TRUE , 0 ) ;
 gtk_widget_show ( button ) ;
 gtk_widget_show ( data_window ) ;
 if ( GTK_IS_WINDOW ( data_window ) ) gtk_window_present ( GTK_WINDOW ( data_window ) ) ;
 else gtkui_page_present ( data_window ) ;
 g_timeout_add ( 500 , gtkui_connections_scroll , & scroll_split ) ;
 connbuf_print ( & curr_conn -> data , split_print ) ;
 conntrack_hook_conn_add ( curr_conn , split_print_po ) ;
 }