static void test_rename ( ) {
 MYSQL_STMT * stmt ;
 const char * query = "rename table t1 to t2, t3 to t4" ;
 int rc ;
 myheader ( "test_table_rename" ) ;
 rc = mysql_query ( mysql , "DROP TABLE IF EXISTS t1, t2, t3, t4" ) ;
 myquery ( rc ) ;
 stmt = mysql_simple_prepare ( mysql , query ) ;
 check_stmt ( stmt ) ;
 rc = mysql_query ( mysql , "create table t1 (a int)" ) ;
 myquery ( rc ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute_r ( stmt , rc ) ;
 if ( ! opt_silent ) fprintf ( stdout , "rename without t3\n" ) ;
 rc = mysql_query ( mysql , "create table t3 (a int)" ) ;
 myquery ( rc ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 if ( ! opt_silent ) fprintf ( stdout , "rename with t3\n" ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute_r ( stmt , rc ) ;
 if ( ! opt_silent ) fprintf ( stdout , "rename renamed\n" ) ;
 rc = mysql_query ( mysql , "rename table t2 to t1, t4 to t3" ) ;
 myquery ( rc ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 if ( ! opt_silent ) fprintf ( stdout , "rename reverted\n" ) ;
 mysql_stmt_close ( stmt ) ;
 rc = mysql_query ( mysql , "DROP TABLE t2, t4" ) ;
 myquery ( rc ) ;
 }