static inline int rsvp_class_to_tree_type ( int classnum ) {
 switch ( classnum ) {
 case RSVP_CLASS_SESSION : return TT_SESSION ;
 case RSVP_CLASS_HOP : return TT_HOP ;
 case RSVP_CLASS_INTEGRITY : return TT_INTEGRITY ;
 case RSVP_CLASS_TIME_VALUES : return TT_TIME_VALUES ;
 case RSVP_CLASS_ERROR : return TT_ERROR ;
 case RSVP_CLASS_SCOPE : return TT_SCOPE ;
 case RSVP_CLASS_STYLE : return TT_STYLE ;
 case RSVP_CLASS_FLOWSPEC : return TT_FLOWSPEC ;
 case RSVP_CLASS_FILTER_SPEC : return TT_FILTER_SPEC ;
 case RSVP_CLASS_SENDER_TEMPLATE : return TT_SENDER_TEMPLATE ;
 case RSVP_CLASS_SENDER_TSPEC : return TT_TSPEC ;
 case RSVP_CLASS_ADSPEC : return TT_ADSPEC ;
 case RSVP_CLASS_POLICY : return TT_POLICY ;
 case RSVP_CLASS_CONFIRM : return TT_CONFIRM ;
 case RSVP_CLASS_RECOVERY_LABEL : case RSVP_CLASS_UPSTREAM_LABEL : case RSVP_CLASS_SUGGESTED_LABEL : case RSVP_CLASS_LABEL : return TT_LABEL ;
 case RSVP_CLASS_LABEL_REQUEST : return TT_LABEL_REQUEST ;
 case RSVP_CLASS_HELLO : return TT_HELLO_OBJ ;
 case RSVP_CLASS_EXPLICIT_ROUTE : return TT_EXPLICIT_ROUTE ;
 case RSVP_CLASS_RECORD_ROUTE : return TT_RECORD_ROUTE ;
 case RSVP_CLASS_MESSAGE_ID : return TT_MESSAGE_ID ;
 case RSVP_CLASS_MESSAGE_ID_ACK : return TT_MESSAGE_ID_ACK ;
 case RSVP_CLASS_MESSAGE_ID_LIST : return TT_MESSAGE_ID_LIST ;
 case RSVP_CLASS_LABEL_SET : return TT_LABEL_SET ;
 case RSVP_CLASS_PROTECTION : return TT_PROTECTION_INFO ;
 case RSVP_CLASS_ACCEPTABLE_LABEL_SET : return TT_UNKNOWN_CLASS ;
 case RSVP_CLASS_RESTART_CAP : return TT_RESTART_CAP ;
 case RSVP_CLASS_LINK_CAP : return TT_LINK_CAP ;
 case RSVP_CLASS_DIFFSERV : return TT_DIFFSERV ;
 case RSVP_CLASS_CLASSTYPE : return TT_CLASSTYPE ;
 case RSVP_CLASS_NOTIFY_REQUEST : return TT_UNKNOWN_CLASS ;
 case RSVP_CLASS_ADMIN_STATUS : return TT_ADMIN_STATUS ;
 case RSVP_CLASS_LSP_ATTRIBUTES : case RSVP_CLASS_LSP_REQUIRED_ATTRIBUTES : return TT_LSP_ATTRIBUTES ;
 case RSVP_CLASS_ASSOCIATION : return TT_ASSOCIATION ;
 case RSVP_CLASS_CALL_ATTRIBUTES : return RSVPF_CALL_ATTRIBUTES ;
 case RSVP_CLASS_JUNIPER_PROPERTIES : return TT_JUNIPER ;
 case RSVP_CLASS_SESSION_ATTRIBUTE : return TT_SESSION_ATTRIBUTE ;
 case RSVP_CLASS_GENERALIZED_UNI : return TT_GEN_UNI ;
 case RSVP_CLASS_CALL_ID : return TT_CALL_ID ;
 case RSVP_CLASS_3GPP2_OBJECT : return TT_3GPP2_OBJECT ;
 case RSVP_CLASS_DCLASS : return TT_DCLASS ;
 case RSVP_CLASS_LSP_TUNNEL_IF_ID : return TT_LSP_TUNNEL_IF_ID ;
 case RSVP_CLASS_EXCLUDE_ROUTE : return TT_EXCLUDE_ROUTE ;
 case RSVP_CLASS_VENDOR_PRIVATE_1 : case RSVP_CLASS_VENDOR_PRIVATE_2 : case RSVP_CLASS_VENDOR_PRIVATE_3 : case RSVP_CLASS_VENDOR_PRIVATE_4 : case RSVP_CLASS_VENDOR_PRIVATE_5 : case RSVP_CLASS_VENDOR_PRIVATE_6 : case RSVP_CLASS_VENDOR_PRIVATE_7 : case RSVP_CLASS_VENDOR_PRIVATE_8 : case RSVP_CLASS_VENDOR_PRIVATE_9 : case RSVP_CLASS_VENDOR_PRIVATE_10 : case RSVP_CLASS_VENDOR_PRIVATE_11 : case RSVP_CLASS_VENDOR_PRIVATE_12 : return TT_PRIVATE_CLASS ;
 default : return TT_UNKNOWN_CLASS ;
 }
 }