static void test_select_show ( ) {
 MYSQL_STMT * stmt ;
 int rc ;
 char query [ MAX_TEST_QUERY_LENGTH ] ;
 myheader ( "test_select_show" ) ;
 mysql_autocommit ( mysql , TRUE ) ;
 rc = mysql_query ( mysql , "DROP TABLE IF EXISTS test_show" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "CREATE TABLE test_show(id int(4) NOT NULL primary " " key, name char(2))" ) ;
 myquery ( rc ) ;
 stmt = mysql_simple_prepare ( mysql , "show columns from test_show" ) ;
 check_stmt ( stmt ) ;
 verify_param_count ( stmt , 0 ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 my_process_stmt_result ( stmt ) ;
 mysql_stmt_close ( stmt ) ;
 stmt = mysql_simple_prepare ( mysql , "show tables from mysql like ?" ) ;
 check_stmt_r ( stmt ) ;
 strxmov ( query , "show tables from " , current_db , " like \'test_show\'" , NullS ) ;
 stmt = mysql_simple_prepare ( mysql , query ) ;
 check_stmt ( stmt ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 my_process_stmt_result ( stmt ) ;
 mysql_stmt_close ( stmt ) ;
 stmt = mysql_simple_prepare ( mysql , "describe test_show" ) ;
 check_stmt ( stmt ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 my_process_stmt_result ( stmt ) ;
 mysql_stmt_close ( stmt ) ;
 stmt = mysql_simple_prepare ( mysql , "show keys from test_show" ) ;
 check_stmt ( stmt ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 rc = my_process_stmt_result ( stmt ) ;
 DIE_UNLESS ( rc == 1 ) ;
 mysql_stmt_close ( stmt ) ;
 }