static void test_bug30472 ( ) {
 MYSQL con ;
 char character_set_name_1 [ MY_CS_NAME_SIZE ] ;
 char character_set_client_1 [ MY_CS_NAME_SIZE ] ;
 char character_set_results_1 [ MY_CS_NAME_SIZE ] ;
 char collation_connnection_1 [ MY_CS_NAME_SIZE ] ;
 char character_set_name_2 [ MY_CS_NAME_SIZE ] ;
 char character_set_client_2 [ MY_CS_NAME_SIZE ] ;
 char character_set_results_2 [ MY_CS_NAME_SIZE ] ;
 char collation_connnection_2 [ MY_CS_NAME_SIZE ] ;
 char character_set_name_3 [ MY_CS_NAME_SIZE ] ;
 char character_set_client_3 [ MY_CS_NAME_SIZE ] ;
 char character_set_results_3 [ MY_CS_NAME_SIZE ] ;
 char collation_connnection_3 [ MY_CS_NAME_SIZE ] ;
 char character_set_name_4 [ MY_CS_NAME_SIZE ] ;
 char character_set_client_4 [ MY_CS_NAME_SIZE ] ;
 char character_set_results_4 [ MY_CS_NAME_SIZE ] ;
 char collation_connnection_4 [ MY_CS_NAME_SIZE ] ;
 DIE_UNLESS ( mysql_client_init ( & con ) ) ;
 DIE_UNLESS ( mysql_real_connect ( & con , opt_host , opt_user , opt_password , opt_db ? opt_db : "test" , opt_port , opt_unix_socket , CLIENT_FOUND_ROWS ) ) ;
 bug30472_retrieve_charset_info ( & con , character_set_name_1 , character_set_client_1 , character_set_results_1 , collation_connnection_1 ) ;
 DIE_IF ( mysql_set_character_set ( & con , "utf8" ) ) ;
 bug30472_retrieve_charset_info ( & con , character_set_name_2 , character_set_client_2 , character_set_results_2 , collation_connnection_2 ) ;
 DIE_UNLESS ( strcmp ( character_set_name_2 , "utf8" ) == 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_client_2 , "utf8" ) == 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_results_2 , "utf8" ) == 0 ) ;
 DIE_UNLESS ( strcmp ( collation_connnection_2 , "utf8_general_ci" ) == 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_name_1 , character_set_name_2 ) != 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_client_1 , character_set_client_2 ) != 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_results_1 , character_set_results_2 ) != 0 ) ;
 DIE_UNLESS ( strcmp ( collation_connnection_1 , collation_connnection_2 ) != 0 ) ;
 DIE_IF ( mysql_change_user ( & con , opt_user , opt_password , opt_db ? opt_db : "test" ) ) ;
 bug30472_retrieve_charset_info ( & con , character_set_name_3 , character_set_client_3 , character_set_results_3 , collation_connnection_3 ) ;
 DIE_UNLESS ( strcmp ( character_set_name_1 , character_set_name_3 ) == 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_client_1 , character_set_client_3 ) == 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_results_1 , character_set_results_3 ) == 0 ) ;
 DIE_UNLESS ( strcmp ( collation_connnection_1 , collation_connnection_3 ) == 0 ) ;
 mysql_options ( & con , MYSQL_SET_CHARSET_NAME , "utf8" ) ;
 DIE_IF ( mysql_change_user ( & con , opt_user , opt_password , opt_db ? opt_db : "test" ) ) ;
 bug30472_retrieve_charset_info ( & con , character_set_name_4 , character_set_client_4 , character_set_results_4 , collation_connnection_4 ) ;
 DIE_UNLESS ( strcmp ( character_set_name_4 , "utf8" ) == 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_client_4 , "utf8" ) == 0 ) ;
 DIE_UNLESS ( strcmp ( character_set_results_4 , "utf8" ) == 0 ) ;
 DIE_UNLESS ( strcmp ( collation_connnection_4 , "utf8_general_ci" ) == 0 ) ;
 mysql_close ( & con ) ;
 }