static void dissect_rsvp_ifid_tlv ( proto_tree * ti , packet_info * pinfo , proto_tree * rsvp_object_tree , tvbuff_t * tvb , int offset , int length , int subtree_type ) {
 int tlv_off , padding ;
 guint16 tlv_type ;
 int tlv_len ;
 guint8 isis_len ;
 const char * tlv_name , * ip_str ;
 proto_tree * rsvp_ifid_subtree = NULL , * ti2 = NULL ;
 for ( tlv_off = 0 ;
 tlv_off < length ;
 ) {
 tlv_type = tvb_get_ntohs ( tvb , offset + tlv_off ) ;
 tlv_len = tvb_get_ntohs ( tvb , offset + tlv_off + 2 ) ;
 if ( ( tlv_len == 0 ) || ( tlv_off + tlv_len > length ) ) {
 proto_tree_add_expert_format ( rsvp_object_tree , pinfo , & ei_rsvp_invalid_length , tvb , offset + tlv_off + 2 , 2 , "Invalid TLV length" ) ;
 return ;
 }
 switch ( tlv_type ) {
 case 1 : tlv_name = "" ;
 goto ifid_ipv4 ;
 case 14 : tlv_name = "Previous-Hop " ;
 goto ifid_ipv4 ;
 case 16 : tlv_name = "Incoming " ;
 ifid_ipv4 : ip_str = tvb_ip_to_str ( tvb , offset + tlv_off + 4 ) ;
 rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "%sIPv4 TLV - %s" , tlv_name , ip_str ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (%sIPv4)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_ipv4_address , tvb , offset + tlv_off + 4 , 4 , ENC_BIG_ENDIAN ) ;
 proto_item_append_text ( ti , "%sIPv4: %s. " , tlv_name , ip_str ) ;
 break ;
 case 2 : tlv_name = "" ;
 goto ifid_ipv6 ;
 case 15 : tlv_name = "Previous-Hop " ;
 goto ifid_ipv6 ;
 case 17 : tlv_name = "Incoming " ;
 ifid_ipv6 : ip_str = tvb_ip6_to_str ( tvb , offset + tlv_off + 4 ) ;
 rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "%sIPv6 TLV - %s" , tlv_name , ip_str ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (%sIPv6)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_ipv6_address , tvb , offset + tlv_off + 4 , 16 , ENC_NA ) ;
 proto_item_append_text ( ti , "%sIPv6: %s. " , tlv_name , ip_str ) ;
 break ;
 case 3 : tlv_name = "" ;
 goto ifid_ifindex ;
 case 4 : tlv_name = " Forward" ;
 goto ifid_ifindex ;
 case 5 : tlv_name = " Reverse" ;
 goto ifid_ifindex ;
 case 18 : tlv_name = " Incoming" ;
 ifid_ifindex : ip_str = tvb_ip_to_str ( tvb , offset + tlv_off + 4 ) ;
 rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "Interface-Index%s TLV - %s, %d" , tlv_name , ip_str , tvb_get_ntohl ( tvb , offset + tlv_off + 8 ) ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (Interface Index%s)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_ipv4_address , tvb , offset + tlv_off + 4 , 4 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlvinterface_id , tvb , offset + tlv_off + 8 , 4 , ENC_BIG_ENDIAN ) ;
 proto_item_append_text ( ti , "Data If-Index%s: %s, %d. " , tlv_name , ip_str , tvb_get_ntohl ( tvb , offset + tlv_off + 8 ) ) ;
 break ;
 case 6 : tlv_name = "Downstream" ;
 goto ifid_label ;
 case 7 : tlv_name = "Upstream" ;
 goto ifid_label ;
 case 19 : tlv_name = "Incoming-Downstream" ;
 goto ifid_label ;
 case 20 : tlv_name = "Incoming-Upstream" ;
 ifid_label : rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "%s-Label TLV - %u" , tlv_name , tvb_get_ntohl ( tvb , offset + tlv_off + 4 ) ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (%s-Label)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_label , tvb , offset + tlv_off + 4 , 4 , ENC_BIG_ENDIAN ) ;
 proto_item_append_text ( ti , "%s-Label: %u. " , tlv_name , tvb_get_ntohl ( tvb , offset + tlv_off + 4 ) ) ;
 break ;
 case 8 : tlv_name = "" ;
 goto ifid_nodeid ;
 case 21 : tlv_name = "Reporting-" ;
 ifid_nodeid : ip_str = tvb_ip_to_str ( tvb , offset + tlv_off + 4 ) ;
 rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "%sNode-ID TLV - %s" , tlv_name , ip_str ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (%sNode-ID)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_node_id , tvb , offset + tlv_off + 4 , 4 , ENC_BIG_ENDIAN ) ;
 proto_item_append_text ( ti , "%sNode-ID: %s. " , tlv_name , ip_str ) ;
 break ;
 case 9 : tlv_name = "" ;
 goto ifid_ospf ;
 case 22 : tlv_name = "Reporting-" ;
 ifid_ospf : rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "%sOSPF-Area TLV - %u" , tlv_name , tvb_get_ntohl ( tvb , offset + tlv_off + 4 ) ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (%sOSPF-Area)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_area , tvb , offset + tlv_off + 4 , 4 , ENC_BIG_ENDIAN ) ;
 proto_item_append_text ( ti , "%sOSPF-Area: %u. " , tlv_name , tvb_get_ntohl ( tvb , offset + tlv_off + 4 ) ) ;
 break ;
 case 10 : tlv_name = "" ;
 goto ifid_isis ;
 case 23 : tlv_name = "Reporting-" ;
 ifid_isis : isis_len = tvb_get_guint8 ( tvb , offset + tlv_off + 4 ) ;
 if ( ( isis_len < 2 ) || ( isis_len > 11 ) ) {
 proto_tree_add_expert_format ( rsvp_object_tree , pinfo , & ei_rsvp_invalid_length , tvb , offset + tlv_off , tlv_len , "%sISIS-Area TLV - Invalid Length field" , tlv_name ) ;
 break ;
 }
 ip_str = print_nsap_net ( tvb , offset + tlv_off + 5 , isis_len ) ;
 rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "%sISIS-Area TLV - %s" , tlv_name , ip_str ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (%sISIS-Area)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_string ( rsvp_ifid_subtree , hf_rsvp_isis_area_id , tvb , offset + tlv_off + 4 , 4 , ip_str ) ;
 proto_item_append_text ( ti , "%sISIS-Area: %s. " , tlv_name , ip_str ) ;
 break ;
 case 11 : tlv_name = "" ;
 goto ifid_as ;
 case 24 : tlv_name = "Reporting-" ;
 ifid_as : rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "%sAS TLV - %u" , tlv_name , tvb_get_ntohl ( tvb , offset + tlv_off + 4 ) ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (%sAS)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_autonomous_system , tvb , offset + tlv_off + 4 , 4 , ENC_BIG_ENDIAN ) ;
 proto_item_append_text ( ti , "%sAS: %u. " , tlv_name , tvb_get_ntohl ( tvb , offset + tlv_off + 4 ) ) ;
 break ;
 case 26 : tlv_name = "Node" ;
 goto ifid_ex ;
 case 27 : tlv_name = "Link" ;
 ifid_ex : rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , & ti2 , "%s-Exclusions TLV - " , tlv_name ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%d (%s-Exclusions)" , tlv_type , tlv_name ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 dissect_rsvp_ifid_tlv ( ti2 , pinfo , rsvp_ifid_subtree , tvb , offset + tlv_off + 4 , tlv_len - 4 , TREE ( TT_HOP_SUBOBJ ) ) ;
 break ;
 case 516 : rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "ERROR_STRING TLV - %s" , tvb_format_text ( tvb , offset + tlv_off + 4 , tlv_len - 4 ) ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "516 (ERROR_STRING)" ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_error_string , tvb , offset + tlv_off + 4 , tlv_len - 4 , ENC_NA | ENC_ASCII ) ;
 break ;
 default : rsvp_ifid_subtree = proto_tree_add_subtree_format ( rsvp_object_tree , tvb , offset + tlv_off , tlv_len , subtree_type , NULL , "Unknown TLV (%u)" , tlv_type ) ;
 proto_tree_add_uint_format_value ( rsvp_ifid_subtree , hf_rsvp_type , tvb , offset + tlv_off , 2 , tlv_type , "%u (Unknown)" , tlv_type ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_length , tvb , offset + tlv_off + 2 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_data , tvb , offset + tlv_off + 4 , tlv_len - 4 , ENC_NA ) ;
 break ;
 }
 padding = ( 4 - ( tlv_len % 4 ) ) % 4 ;
 if ( padding != 0 ) proto_tree_add_item ( rsvp_ifid_subtree , hf_rsvp_ifid_tlv_padding , tvb , offset + tlv_off + tlv_len , padding , ENC_NA ) ;
 tlv_off += tlv_len + padding ;
 }
 }