void chat_completion_init ( void ) {
 settings_add_str ( "completion" , "completion_char" , ":" ) ;
 settings_add_bool ( "completion" , "completion_auto" , FALSE ) ;
 settings_add_int ( "completion" , "completion_keep_publics" , 50 ) ;
 settings_add_int ( "completion" , "completion_keep_privates" , 10 ) ;
 settings_add_bool ( "completion" , "completion_nicks_lowercase" , FALSE ) ;
 settings_add_bool ( "completion" , "completion_strict" , FALSE ) ;
 settings_add_bool ( "completion" , "completion_empty_line" , TRUE ) ;
 settings_add_choice ( "completion" , "completion_nicks_match_case" , COMPLETE_MCASE_AUTO , "never;
always;
auto" ) ;
 settings_add_bool ( "lookandfeel" , "expand_escapes" , FALSE ) ;
 read_settings ( ) ;
 signal_add ( "complete word" , ( SIGNAL_FUNC ) sig_complete_word ) ;
 signal_add ( "complete command msg" , ( SIGNAL_FUNC ) sig_complete_msg ) ;
 signal_add ( "complete command query" , ( SIGNAL_FUNC ) sig_complete_msg ) ;
 signal_add ( "complete command action" , ( SIGNAL_FUNC ) sig_complete_msg ) ;
 signal_add ( "complete erase command msg" , ( SIGNAL_FUNC ) sig_erase_complete_msg ) ;
 signal_add ( "complete erase command query" , ( SIGNAL_FUNC ) sig_erase_complete_msg ) ;
 signal_add ( "complete erase command action" , ( SIGNAL_FUNC ) sig_erase_complete_msg ) ;
 signal_add ( "complete command connect" , ( SIGNAL_FUNC ) sig_complete_connect ) ;
 signal_add ( "complete command server" , ( SIGNAL_FUNC ) sig_complete_connect ) ;
 signal_add ( "complete command disconnect" , ( SIGNAL_FUNC ) sig_complete_tag ) ;
 signal_add ( "complete command reconnect" , ( SIGNAL_FUNC ) sig_complete_tag ) ;
 signal_add ( "complete command window server" , ( SIGNAL_FUNC ) sig_complete_tag ) ;
 signal_add ( "complete command topic" , ( SIGNAL_FUNC ) sig_complete_topic ) ;
 signal_add ( "complete command away" , ( SIGNAL_FUNC ) sig_complete_away ) ;
 signal_add ( "complete command unalias" , ( SIGNAL_FUNC ) sig_complete_unalias ) ;
 signal_add ( "complete command alias" , ( SIGNAL_FUNC ) sig_complete_alias ) ;
 signal_add ( "complete command window goto" , ( SIGNAL_FUNC ) sig_complete_window ) ;
 signal_add ( "complete command window item move" , ( SIGNAL_FUNC ) sig_complete_channel ) ;
 signal_add ( "complete command server add" , ( SIGNAL_FUNC ) sig_complete_server ) ;
 signal_add ( "complete command server remove" , ( SIGNAL_FUNC ) sig_complete_server ) ;
 signal_add ( "complete command recode remove" , ( SIGNAL_FUNC ) sig_complete_target ) ;
 signal_add ( "message public" , ( SIGNAL_FUNC ) sig_message_public ) ;
 signal_add ( "message join" , ( SIGNAL_FUNC ) sig_message_join ) ;
 signal_add ( "message private" , ( SIGNAL_FUNC ) sig_message_private ) ;
 signal_add ( "message own_public" , ( SIGNAL_FUNC ) sig_message_own_public ) ;
 signal_add ( "message own_private" , ( SIGNAL_FUNC ) sig_message_own_private ) ;
 signal_add ( "nicklist remove" , ( SIGNAL_FUNC ) sig_nick_removed ) ;
 signal_add ( "nicklist changed" , ( SIGNAL_FUNC ) sig_nick_changed ) ;
 signal_add ( "send text" , ( SIGNAL_FUNC ) event_text ) ;
 signal_add ( "server disconnected" , ( SIGNAL_FUNC ) sig_server_disconnected ) ;
 signal_add ( "channel destroyed" , ( SIGNAL_FUNC ) sig_channel_destroyed ) ;
 signal_add ( "setup changed" , ( SIGNAL_FUNC ) read_settings ) ;
 }