void Init_ossl_asn1 ( void ) {
 VALUE ary ;
 int i ;

 eOSSLError = rb_define_class_under ( mOSSL , "OpenSSLError" , rb_eStandardError ) ;

 sym_CONTEXT_SPECIFIC = ID2SYM ( rb_intern_const ( "CONTEXT_SPECIFIC" ) ) ;
 sym_APPLICATION = ID2SYM ( rb_intern_const ( "APPLICATION" ) ) ;
 sym_PRIVATE = ID2SYM ( rb_intern_const ( "PRIVATE" ) ) ;
 sym_EXPLICIT = ID2SYM ( rb_intern_const ( "EXPLICIT" ) ) ;
 sym_IMPLICIT = ID2SYM ( rb_intern_const ( "IMPLICIT" ) ) ;
 sivVALUE = rb_intern ( "@value" ) ;
 sivTAG = rb_intern ( "@tag" ) ;
 sivTAGGING = rb_intern ( "@tagging" ) ;
 sivTAG_CLASS = rb_intern ( "@tag_class" ) ;
 sivINFINITE_LENGTH = rb_intern ( "@infinite_length" ) ;
 sivUNUSED_BITS = rb_intern ( "@unused_bits" ) ;
 mASN1 = rb_define_module_under ( mOSSL , "ASN1" ) ;
 eASN1Error = rb_define_class_under ( mASN1 , "ASN1Error" , eOSSLError ) ;
 rb_define_module_function ( mASN1 , "traverse" , ossl_asn1_traverse , 1 ) ;
 rb_define_module_function ( mASN1 , "decode" , ossl_asn1_decode , 1 ) ;
 rb_define_module_function ( mASN1 , "decode_all" , ossl_asn1_decode_all , 1 ) ;
 ary = rb_ary_new ( ) ;
 rb_define_const ( mASN1 , "UNIVERSAL_TAG_NAME" , ary ) ;
 for ( i = 0 ;
 i < ossl_asn1_info_size ;
 i ++ ) {
 if ( ossl_asn1_info [ i ] . name [ 0 ] == '[' ) continue ;
 rb_define_const ( mASN1 , ossl_asn1_info [ i ] . name , INT2NUM ( i ) ) ;
 rb_ary_store ( ary , i , rb_str_new2 ( ossl_asn1_info [ i ] . name ) ) ;
 }
 cASN1Data = rb_define_class_under ( mASN1 , "ASN1Data" , rb_cObject ) ;
 rb_attr ( cASN1Data , rb_intern ( "value" ) , 1 , 1 , 0 ) ;
 rb_attr ( cASN1Data , rb_intern ( "tag" ) , 1 , 1 , 0 ) ;
 rb_attr ( cASN1Data , rb_intern ( "tag_class" ) , 1 , 1 , 0 ) ;
 rb_attr ( cASN1Data , rb_intern ( "infinite_length" ) , 1 , 1 , 0 ) ;
 rb_define_method ( cASN1Data , "initialize" , ossl_asn1data_initialize , 3 ) ;
 rb_define_method ( cASN1Data , "to_der" , ossl_asn1data_to_der , 0 ) ;
 cASN1Primitive = rb_define_class_under ( mASN1 , "Primitive" , cASN1Data ) ;
 rb_attr ( cASN1Primitive , rb_intern ( "tagging" ) , 1 , 1 , Qtrue ) ;
 rb_undef_method ( cASN1Primitive , "infinite_length=" ) ;
 rb_define_method ( cASN1Primitive , "initialize" , ossl_asn1_initialize , - 1 ) ;
 rb_define_method ( cASN1Primitive , "to_der" , ossl_asn1prim_to_der , 0 ) ;
 cASN1Constructive = rb_define_class_under ( mASN1 , "Constructive" , cASN1Data ) ;
 rb_include_module ( cASN1Constructive , rb_mEnumerable ) ;
 rb_attr ( cASN1Constructive , rb_intern ( "tagging" ) , 1 , 1 , Qtrue ) ;
 rb_define_method ( cASN1Constructive , "initialize" , ossl_asn1_initialize , - 1 ) ;
 rb_define_method ( cASN1Constructive , "to_der" , ossl_asn1cons_to_der , 0 ) ;
 rb_define_method ( cASN1Constructive , "each" , ossl_asn1cons_each , 0 ) ;

 cASN1 ## name = rb_define_class_under ( mASN1 , # name , cASN1 ## super ) ;
 rb_define_module_function ( mASN1 , # name , ossl_asn1_ ## name , - 1 ) ;
 \ }
 while ( 0 ) OSSL_ASN1_DEFINE_CLASS ( Boolean , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( Integer , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( Enumerated , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( BitString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( OctetString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( UTF8String , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( NumericString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( PrintableString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( T61String , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( VideotexString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( IA5String , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( GraphicString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( ISO64String , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( GeneralString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( UniversalString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( BMPString , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( Null , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( ObjectId , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( UTCTime , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( GeneralizedTime , Primitive ) ;
 OSSL_ASN1_DEFINE_CLASS ( Sequence , Constructive ) ;
 OSSL_ASN1_DEFINE_CLASS ( Set , Constructive ) ;
 OSSL_ASN1_DEFINE_CLASS ( EndOfContent , Data ) ;


 rb_define_method ( cASN1ObjectId , "sn" , ossl_asn1obj_get_sn , 0 ) ;
 rb_define_method ( cASN1ObjectId , "ln" , ossl_asn1obj_get_ln , 0 ) ;
 rb_define_method ( cASN1ObjectId , "oid" , ossl_asn1obj_get_oid , 0 ) ;
 rb_define_alias ( cASN1ObjectId , "short_name" , "sn" ) ;
 rb_define_alias ( cASN1ObjectId , "long_name" , "ln" ) ;
 rb_attr ( cASN1BitString , rb_intern ( "unused_bits" ) , 1 , 1 , 0 ) ;
 rb_define_method ( cASN1EndOfContent , "initialize" , ossl_asn1eoc_initialize , 0 ) ;
 class_tag_map = rb_hash_new ( ) ;
 rb_hash_aset ( class_tag_map , cASN1EndOfContent , INT2NUM ( V_ASN1_EOC ) ) ;
 rb_hash_aset ( class_tag_map , cASN1Boolean , INT2NUM ( V_ASN1_BOOLEAN ) ) ;
 rb_hash_aset ( class_tag_map , cASN1Integer , INT2NUM ( V_ASN1_INTEGER ) ) ;
 rb_hash_aset ( class_tag_map , cASN1BitString , INT2NUM ( V_ASN1_BIT_STRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1OctetString , INT2NUM ( V_ASN1_OCTET_STRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1Null , INT2NUM ( V_ASN1_NULL ) ) ;
 rb_hash_aset ( class_tag_map , cASN1ObjectId , INT2NUM ( V_ASN1_OBJECT ) ) ;
 rb_hash_aset ( class_tag_map , cASN1Enumerated , INT2NUM ( V_ASN1_ENUMERATED ) ) ;
 rb_hash_aset ( class_tag_map , cASN1UTF8String , INT2NUM ( V_ASN1_UTF8STRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1Sequence , INT2NUM ( V_ASN1_SEQUENCE ) ) ;
 rb_hash_aset ( class_tag_map , cASN1Set , INT2NUM ( V_ASN1_SET ) ) ;
 rb_hash_aset ( class_tag_map , cASN1NumericString , INT2NUM ( V_ASN1_NUMERICSTRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1PrintableString , INT2NUM ( V_ASN1_PRINTABLESTRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1T61String , INT2NUM ( V_ASN1_T61STRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1VideotexString , INT2NUM ( V_ASN1_VIDEOTEXSTRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1IA5String , INT2NUM ( V_ASN1_IA5STRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1UTCTime , INT2NUM ( V_ASN1_UTCTIME ) ) ;
 rb_hash_aset ( class_tag_map , cASN1GeneralizedTime , INT2NUM ( V_ASN1_GENERALIZEDTIME ) ) ;
 rb_hash_aset ( class_tag_map , cASN1GraphicString , INT2NUM ( V_ASN1_GRAPHICSTRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1ISO64String , INT2NUM ( V_ASN1_ISO64STRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1GeneralString , INT2NUM ( V_ASN1_GENERALSTRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1UniversalString , INT2NUM ( V_ASN1_UNIVERSALSTRING ) ) ;
 rb_hash_aset ( class_tag_map , cASN1BMPString , INT2NUM ( V_ASN1_BMPSTRING ) ) ;
 rb_global_variable ( & class_tag_map ) ;
 }