void Init_generator ( void ) {
 rb_require ( "json/common" ) ;
 mJSON = rb_define_module ( "JSON" ) ;
 mExt = rb_define_module_under ( mJSON , "Ext" ) ;
 mGenerator = rb_define_module_under ( mExt , "Generator" ) ;
 eGeneratorError = rb_path2class ( "JSON::GeneratorError" ) ;
 eNestingError = rb_path2class ( "JSON::NestingError" ) ;
 cState = rb_define_class_under ( mGenerator , "State" , rb_cObject ) ;
 rb_define_alloc_func ( cState , cState_s_allocate ) ;
 rb_define_singleton_method ( cState , "from_state" , cState_from_state_s , 1 ) ;
 rb_define_method ( cState , "initialize" , cState_initialize , - 1 ) ;
 rb_define_method ( cState , "initialize_copy" , cState_init_copy , 1 ) ;
 rb_define_method ( cState , "indent" , cState_indent , 0 ) ;
 rb_define_method ( cState , "indent=" , cState_indent_set , 1 ) ;
 rb_define_method ( cState , "space" , cState_space , 0 ) ;
 rb_define_method ( cState , "space=" , cState_space_set , 1 ) ;
 rb_define_method ( cState , "space_before" , cState_space_before , 0 ) ;
 rb_define_method ( cState , "space_before=" , cState_space_before_set , 1 ) ;
 rb_define_method ( cState , "object_nl" , cState_object_nl , 0 ) ;
 rb_define_method ( cState , "object_nl=" , cState_object_nl_set , 1 ) ;
 rb_define_method ( cState , "array_nl" , cState_array_nl , 0 ) ;
 rb_define_method ( cState , "array_nl=" , cState_array_nl_set , 1 ) ;
 rb_define_method ( cState , "max_nesting" , cState_max_nesting , 0 ) ;
 rb_define_method ( cState , "max_nesting=" , cState_max_nesting_set , 1 ) ;
 rb_define_method ( cState , "check_circular?" , cState_check_circular_p , 0 ) ;
 rb_define_method ( cState , "allow_nan?" , cState_allow_nan_p , 0 ) ;
 rb_define_method ( cState , "ascii_only?" , cState_ascii_only_p , 0 ) ;
 rb_define_method ( cState , "depth" , cState_depth , 0 ) ;
 rb_define_method ( cState , "depth=" , cState_depth_set , 1 ) ;
 rb_define_method ( cState , "buffer_initial_length" , cState_buffer_initial_length , 0 ) ;
 rb_define_method ( cState , "buffer_initial_length=" , cState_buffer_initial_length_set , 1 ) ;
 rb_define_method ( cState , "configure" , cState_configure , 1 ) ;
 rb_define_alias ( cState , "merge" , "configure" ) ;
 rb_define_method ( cState , "to_h" , cState_to_h , 0 ) ;
 rb_define_alias ( cState , "to_hash" , "to_h" ) ;
 rb_define_method ( cState , "[]" , cState_aref , 1 ) ;
 rb_define_method ( cState , "[]=" , cState_aset , 2 ) ;
 rb_define_method ( cState , "generate" , cState_generate , 1 ) ;
 mGeneratorMethods = rb_define_module_under ( mGenerator , "GeneratorMethods" ) ;
 mObject = rb_define_module_under ( mGeneratorMethods , "Object" ) ;
 rb_define_method ( mObject , "to_json" , mObject_to_json , - 1 ) ;
 mHash = rb_define_module_under ( mGeneratorMethods , "Hash" ) ;
 rb_define_method ( mHash , "to_json" , mHash_to_json , - 1 ) ;
 mArray = rb_define_module_under ( mGeneratorMethods , "Array" ) ;
 rb_define_method ( mArray , "to_json" , mArray_to_json , - 1 ) ;

 rb_define_method ( mInteger , "to_json" , mInteger_to_json , - 1 ) ;

 rb_define_method ( mFixnum , "to_json" , mFixnum_to_json , - 1 ) ;
 mBignum = rb_define_module_under ( mGeneratorMethods , "Bignum" ) ;
 rb_define_method ( mBignum , "to_json" , mBignum_to_json , - 1 ) ;

 rb_define_method ( mFloat , "to_json" , mFloat_to_json , - 1 ) ;
 mString = rb_define_module_under ( mGeneratorMethods , "String" ) ;
 rb_define_singleton_method ( mString , "included" , mString_included_s , 1 ) ;
 rb_define_method ( mString , "to_json" , mString_to_json , - 1 ) ;
 rb_define_method ( mString , "to_json_raw" , mString_to_json_raw , - 1 ) ;
 rb_define_method ( mString , "to_json_raw_object" , mString_to_json_raw_object , 0 ) ;
 mString_Extend = rb_define_module_under ( mString , "Extend" ) ;
 rb_define_method ( mString_Extend , "json_create" , mString_Extend_json_create , 1 ) ;
 mTrueClass = rb_define_module_under ( mGeneratorMethods , "TrueClass" ) ;
 rb_define_method ( mTrueClass , "to_json" , mTrueClass_to_json , - 1 ) ;
 mFalseClass = rb_define_module_under ( mGeneratorMethods , "FalseClass" ) ;
 rb_define_method ( mFalseClass , "to_json" , mFalseClass_to_json , - 1 ) ;
 mNilClass = rb_define_module_under ( mGeneratorMethods , "NilClass" ) ;
 rb_define_method ( mNilClass , "to_json" , mNilClass_to_json , - 1 ) ;
 CRegexp_MULTILINE = rb_const_get ( rb_cRegexp , rb_intern ( "MULTILINE" ) ) ;
 i_to_s = rb_intern ( "to_s" ) ;
 i_to_json = rb_intern ( "to_json" ) ;
 i_new = rb_intern ( "new" ) ;
 i_indent = rb_intern ( "indent" ) ;
 i_space = rb_intern ( "space" ) ;
 i_space_before = rb_intern ( "space_before" ) ;
 i_object_nl = rb_intern ( "object_nl" ) ;
 i_array_nl = rb_intern ( "array_nl" ) ;
 i_max_nesting = rb_intern ( "max_nesting" ) ;
 i_allow_nan = rb_intern ( "allow_nan" ) ;
 i_ascii_only = rb_intern ( "ascii_only" ) ;
 i_depth = rb_intern ( "depth" ) ;
 i_buffer_initial_length = rb_intern ( "buffer_initial_length" ) ;
 i_pack = rb_intern ( "pack" ) ;
 i_unpack = rb_intern ( "unpack" ) ;
 i_create_id = rb_intern ( "create_id" ) ;
 i_extend = rb_intern ( "extend" ) ;
 i_key_p = rb_intern ( "key?" ) ;
 i_aref = rb_intern ( "[]" ) ;
 i_send = rb_intern ( "__send__" ) ;
 i_respond_to_p = rb_intern ( "respond_to?" ) ;
 i_match = rb_intern ( "match" ) ;
 i_keys = rb_intern ( "keys" ) ;
 i_dup = rb_intern ( "dup" ) ;

 i_encoding = rb_intern ( "encoding" ) ;
 i_encode = rb_intern ( "encode" ) ;

 CJSON_SAFE_STATE_PROTOTYPE = Qnil ;
 }