static void test_open_direct ( ) {
 MYSQL_STMT * stmt ;
 MYSQL_RES * result ;
 int rc ;
 myheader ( "test_open_direct" ) ;
 rc = mysql_query ( mysql , "DROP TABLE IF EXISTS test_open_direct" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "CREATE TABLE test_open_direct(id int, name char(6))" ) ;
 myquery ( rc ) ;
 stmt = mysql_simple_prepare ( mysql , "INSERT INTO test_open_direct values(10, 'mysql')" ) ;
 check_stmt ( stmt ) ;
 rc = mysql_query ( mysql , "SELECT * FROM test_open_direct" ) ;
 myquery ( rc ) ;
 result = mysql_store_result ( mysql ) ;
 mytest ( result ) ;
 rc = my_process_result_set ( result ) ;
 DIE_UNLESS ( rc == 0 ) ;
 mysql_free_result ( result ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 verify_st_affected_rows ( stmt , 1 ) ;
 rc = mysql_query ( mysql , "SELECT * FROM test_open_direct" ) ;
 myquery ( rc ) ;
 result = mysql_store_result ( mysql ) ;
 mytest ( result ) ;
 rc = my_process_result_set ( result ) ;
 DIE_UNLESS ( rc == 1 ) ;
 mysql_free_result ( result ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 verify_st_affected_rows ( stmt , 1 ) ;
 rc = mysql_query ( mysql , "SELECT * FROM test_open_direct" ) ;
 myquery ( rc ) ;
 result = mysql_store_result ( mysql ) ;
 mytest ( result ) ;
 rc = my_process_result_set ( result ) ;
 DIE_UNLESS ( rc == 2 ) ;
 mysql_free_result ( result ) ;
 mysql_stmt_close ( stmt ) ;
 stmt = mysql_simple_prepare ( mysql , "SELECT * FROM test_open_direct" ) ;
 check_stmt ( stmt ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_stmt_fetch ( stmt ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_query ( mysql , "INSERT INTO test_open_direct(id) VALUES(20)" ) ;
 myquery_r ( rc ) ;
 rc = mysql_stmt_close ( stmt ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_query ( mysql , "INSERT INTO test_open_direct(id) VALUES(20)" ) ;
 myquery ( rc ) ;
 stmt = mysql_simple_prepare ( mysql , "SELECT * FROM test_open_direct" ) ;
 check_stmt ( stmt ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_stmt_store_result ( stmt ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_stmt_fetch ( stmt ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_query ( mysql , "drop table test_open_direct" ) ;
 myquery ( rc ) ;
 rc = mysql_stmt_close ( stmt ) ;
 check_execute ( stmt , rc ) ;
 }