PKCS8_PRIV_KEY_INFO * d2i_PKCS8_PRIV_KEY_INFO_fp ( FILE * fp , PKCS8_PRIV_KEY_INFO * * p8inf ) {
 return ASN1_d2i_fp_of ( PKCS8_PRIV_KEY_INFO , PKCS8_PRIV_KEY_INFO_new , d2i_PKCS8_PRIV_KEY_INFO , fp , p8inf ) ;
 }