static void dissect_rsvp_session ( proto_item * ti , proto_tree * rsvp_object_tree , tvbuff_t * tvb , int offset , int obj_length , int rsvp_class _U_ , int type , rsvp_conversation_info * rsvph ) {
 proto_item * hidden_item ;
 int offset2 = offset + 4 ;
 proto_item_set_text ( ti , "%s" , summary_session ( tvb , offset ) ) ;
 switch ( type ) {
 case RSVP_SESSION_TYPE_IPV4 : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , type , "1 - IPv4" ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_IP ] , tvb , offset2 , 4 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_PROTO ] , tvb , offset2 + 4 , 1 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_flags , tvb , offset2 + 5 , 1 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_PORT ] , tvb , offset2 + 6 , 2 , ENC_BIG_ENDIAN ) ;
 rsvph -> session_type = RSVP_SESSION_TYPE_IPV4 ;
 set_address_tvb ( & rsvph -> destination , AT_IPv4 , 4 , tvb , offset2 ) ;
 rsvph -> protocol = tvb_get_guint8 ( tvb , offset2 + 4 ) ;
 rsvph -> udp_dest_port = tvb_get_ntohs ( tvb , offset2 + 6 ) ;
 break ;
 case RSVP_SESSION_TYPE_IPV6 : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , type , "2 - IPv6" ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_destination_address , tvb , offset2 , 16 , ENC_NA ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_protocol , tvb , offset2 + 16 , 1 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_flags , tvb , offset2 + 17 , 1 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_destination_port , tvb , offset2 + 18 , 2 , ENC_BIG_ENDIAN ) ;
 rsvph -> session_type = RSVP_SESSION_TYPE_IPV6 ;
 break ;
 case RSVP_SESSION_TYPE_IPV4_LSP : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , type , "7 - IPv4 LSP" ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_IP ] , tvb , offset2 , 4 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_SHORT_CALL_ID ] , tvb , offset2 + 4 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_TUNNEL_ID ] , tvb , offset2 + 6 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_extended_tunnel_id , tvb , offset2 + 8 , 4 , tvb_get_ntohl ( tvb , offset2 + 8 ) , "%u (%s)" , tvb_get_ntohl ( tvb , offset2 + 8 ) , tvb_ip_to_str ( tvb , offset2 + 8 ) ) ;
 hidden_item = proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_EXT_TUNNEL_ID ] , tvb , offset2 + 8 , 4 , ENC_BIG_ENDIAN ) ;
 PROTO_ITEM_SET_HIDDEN ( hidden_item ) ;
 rsvph -> session_type = RSVP_SESSION_TYPE_IPV4_LSP ;
 set_address_tvb ( & rsvph -> destination , AT_IPv4 , 4 , tvb , offset2 ) ;
 rsvph -> udp_dest_port = tvb_get_ntohs ( tvb , offset2 + 6 ) ;
 rsvph -> ext_tunnel_id = tvb_get_ntohl ( tvb , offset2 + 8 ) ;
 break ;
 case RSVP_SESSION_TYPE_IPV6_LSP : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , type , "8 - IPv6 LSP" ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_IP ] , tvb , offset2 , 16 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_SHORT_CALL_ID ] , tvb , offset2 + 16 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_TUNNEL_ID ] , tvb , offset2 + 18 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_extended_tunnel_ipv6 , tvb , offset2 + 20 , 16 , ENC_NA ) ;
 proto_item_set_text ( ti , "Extended Tunnel ID: (%s)" , tvb_ip6_to_str ( tvb , offset2 + 20 ) ) ;
 hidden_item = proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_EXT_TUNNEL_ID_IPV6 ] , tvb , offset2 + 20 , 16 , ENC_NA ) ;
 PROTO_ITEM_SET_HIDDEN ( hidden_item ) ;
 rsvph -> session_type = RSVP_SESSION_TYPE_IPV6_LSP ;
 set_address_tvb ( & rsvph -> destination , AT_IPv6 , 16 , tvb , offset2 ) ;
 rsvph -> udp_dest_port = tvb_get_ntohs ( tvb , offset2 + 18 ) ;
 rsvph -> ext_tunnel_id_ipv6_pre = tvb_get_ntoh64 ( tvb , offset2 + 20 ) ;
 rsvph -> ext_tunnel_id_ipv6_post = tvb_get_ntoh64 ( tvb , offset2 + 28 ) ;
 break ;
 case RSVP_SESSION_TYPE_AGGREGATE_IPV4 : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , type , "9 - IPv4 Aggregate" ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_IP ] , tvb , offset2 , 4 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_dscp , tvb , offset2 + 7 , 1 , ENC_BIG_ENDIAN ) ;
 rsvph -> session_type = RSVP_SESSION_TYPE_AGGREGATE_IPV4 ;
 set_address_tvb ( & rsvph -> destination , AT_IPv4 , 4 , tvb , offset2 ) ;
 rsvph -> dscp = tvb_get_guint8 ( tvb , offset2 + 7 ) ;
 rsvph -> ext_tunnel_id = tvb_get_ntohl ( tvb , offset2 + 8 ) ;
 break ;
 case RSVP_SESSION_TYPE_IPV4_UNI : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , type , "11 - IPv4 UNI" ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_IP ] , tvb , offset2 , 4 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_TUNNEL_ID ] , tvb , offset2 + 6 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_extended_ipv4_address , tvb , offset2 + 8 , 4 , ENC_BIG_ENDIAN ) ;
 hidden_item = proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_EXT_TUNNEL_ID ] , tvb , offset2 + 8 , 4 , ENC_BIG_ENDIAN ) ;
 PROTO_ITEM_SET_HIDDEN ( hidden_item ) ;
 rsvph -> session_type = RSVP_SESSION_TYPE_IPV4_UNI ;
 set_address_tvb ( & rsvph -> destination , AT_IPv4 , 4 , tvb , offset2 ) ;
 rsvph -> udp_dest_port = tvb_get_ntohs ( tvb , offset2 + 6 ) ;
 rsvph -> ext_tunnel_id = tvb_get_ntohl ( tvb , offset2 + 8 ) ;
 break ;
 case RSVP_SESSION_TYPE_P2MP_LSP_TUNNEL_IPV4 : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , RSVP_SESSION_TYPE_P2MP_LSP_TUNNEL_IPV4 , "13 - IPv4 P2MP LSP TUNNEL" ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_IP ] , tvb , offset2 , 4 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_TUNNEL_ID ] , tvb , offset2 + 6 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_extended_tunnel , tvb , offset2 + 8 , 4 , ENC_BIG_ENDIAN ) ;
 hidden_item = proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_EXT_TUNNEL_ID ] , tvb , offset2 + 8 , 4 , ENC_BIG_ENDIAN ) ;
 PROTO_ITEM_SET_HIDDEN ( hidden_item ) ;
 rsvph -> session_type = RSVP_SESSION_TYPE_P2MP_LSP_TUNNEL_IPV4 ;
 set_address_tvb ( & rsvph -> destination , AT_IPv4 , 4 , tvb , offset2 ) ;
 rsvph -> udp_dest_port = tvb_get_ntohs ( tvb , offset2 + 6 ) ;
 rsvph -> ext_tunnel_id = tvb_get_ntohl ( tvb , offset2 + 8 ) ;
 break ;
 case RSVP_SESSION_TYPE_IPV4_E_NNI : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , type , "15 - IPv4 E-NNI" ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_IP ] , tvb , offset2 , 4 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_TUNNEL_ID ] , tvb , offset2 + 6 , 2 , ENC_BIG_ENDIAN ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_extended_ipv4_address , tvb , offset2 + 8 , 4 , ENC_BIG_ENDIAN ) ;
 hidden_item = proto_tree_add_item ( rsvp_object_tree , hf_rsvp_filter [ RSVPF_SESSION_EXT_TUNNEL_ID ] , tvb , offset2 + 8 , 4 , ENC_BIG_ENDIAN ) ;
 PROTO_ITEM_SET_HIDDEN ( hidden_item ) ;
 rsvph -> session_type = RSVP_SESSION_TYPE_IPV4_E_NNI ;
 set_address_tvb ( & rsvph -> destination , AT_IPv4 , 4 , tvb , offset2 ) ;
 rsvph -> udp_dest_port = tvb_get_ntohs ( tvb , offset2 + 6 ) ;
 rsvph -> ext_tunnel_id = tvb_get_ntohl ( tvb , offset2 + 8 ) ;
 break ;
 default : proto_tree_add_uint_format_value ( rsvp_object_tree , hf_rsvp_ctype , tvb , offset + 3 , 1 , type , "Unknown (%u)" , type ) ;
 proto_tree_add_item ( rsvp_object_tree , hf_rsvp_session_data , tvb , offset2 , obj_length - 4 , ENC_NA ) ;
 break ;
 }
 }