static void x8_ac_compensation ( IntraX8Context * const w , int const direction , int const dc_level ) {
 MpegEncContext * const s = w -> s ;
 int t ;

 switch ( direction ) {
 case 0 : t = T ( 3811 ) ;
 B ( 1 , 0 ) -= t ;
 B ( 0 , 1 ) -= t ;
 t = T ( 487 ) ;
 B ( 2 , 0 ) -= t ;
 B ( 0 , 2 ) -= t ;
 t = T ( 506 ) ;
 B ( 3 , 0 ) -= t ;
 B ( 0 , 3 ) -= t ;
 t = T ( 135 ) ;
 B ( 4 , 0 ) -= t ;
 B ( 0 , 4 ) -= t ;
 B ( 2 , 1 ) += t ;
 B ( 1 , 2 ) += t ;
 B ( 3 , 1 ) += t ;
 B ( 1 , 3 ) += t ;
 t = T ( 173 ) ;
 B ( 5 , 0 ) -= t ;
 B ( 0 , 5 ) -= t ;
 t = T ( 61 ) ;
 B ( 6 , 0 ) -= t ;
 B ( 0 , 6 ) -= t ;
 B ( 5 , 1 ) += t ;
 B ( 1 , 5 ) += t ;
 t = T ( 42 ) ;
 B ( 7 , 0 ) -= t ;
 B ( 0 , 7 ) -= t ;
 B ( 4 , 1 ) += t ;
 B ( 1 , 4 ) += t ;
 B ( 4 , 4 ) += t ;
 t = T ( 1084 ) ;
 B ( 1 , 1 ) += t ;
 s -> block_last_index [ 0 ] = FFMAX ( s -> block_last_index [ 0 ] , 7 * 8 ) ;
 break ;
 case 1 : B ( 0 , 1 ) -= T ( 6269 ) ;
 B ( 0 , 3 ) -= T ( 708 ) ;
 B ( 0 , 5 ) -= T ( 172 ) ;
 B ( 0 , 7 ) -= T ( 73 ) ;
 s -> block_last_index [ 0 ] = FFMAX ( s -> block_last_index [ 0 ] , 7 * 8 ) ;
 break ;
 case 2 : B ( 1 , 0 ) -= T ( 6269 ) ;
 B ( 3 , 0 ) -= T ( 708 ) ;
 B ( 5 , 0 ) -= T ( 172 ) ;
 B ( 7 , 0 ) -= T ( 73 ) ;
 s -> block_last_index [ 0 ] = FFMAX ( s -> block_last_index [ 0 ] , 7 ) ;
 break ;
 }
