static void test_bug13524 ( ) {
 MYSQL_STMT * stmt ;
 int rc ;
 unsigned int warning_count ;
 const ulong type = CURSOR_TYPE_READ_ONLY ;
 const char * query = "select * from t1" ;
 myheader ( "test_bug13524" ) ;
 rc = mysql_query ( mysql , "drop table if exists t1, t2" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "create table t1 (a int not null primary key)" ) ;
 myquery ( rc ) ;
 rc = mysql_query ( mysql , "insert into t1 values (1), (2), (3), (4)" ) ;
 myquery ( rc ) ;
 stmt = mysql_stmt_init ( mysql ) ;
 rc = mysql_stmt_attr_set ( stmt , STMT_ATTR_CURSOR_TYPE , ( const void * ) & type ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_stmt_prepare ( stmt , query , strlen ( query ) ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_stmt_execute ( stmt ) ;
 check_execute ( stmt , rc ) ;
 rc = mysql_stmt_fetch ( stmt ) ;
 check_execute ( stmt , rc ) ;
 warning_count = mysql_warning_count ( mysql ) ;
 DIE_UNLESS ( warning_count == 0 ) ;
 rc = mysql_query ( mysql , "drop table if exists t2" ) ;
 myquery ( rc ) ;
 warning_count = mysql_warning_count ( mysql ) ;
 DIE_UNLESS ( warning_count == 1 ) ;
 rc = mysql_stmt_fetch ( stmt ) ;
 check_execute ( stmt , rc ) ;
 warning_count = mysql_warning_count ( mysql ) ;
 DIE_UNLESS ( warning_count == 0 ) ;
 mysql_stmt_close ( stmt ) ;
 rc = mysql_query ( mysql , "drop table t1" ) ;
 myquery ( rc ) ;
 }