void nautilus_self_check_file_operations ( void ) {
 setlocale ( LC_MESSAGES , "C" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( " (copy)" , 1 , - 1 ) , " (another copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo" , 1 , - 1 ) , "foo (copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( ".bashrc" , 1 , - 1 ) , ".bashrc (copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( ".foo.txt" , 1 , - 1 ) , ".foo (copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo foo" , 1 , - 1 ) , "foo foo (copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo.txt" , 1 , - 1 ) , "foo (copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo foo.txt" , 1 , - 1 ) , "foo foo (copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo foo.txt txt" , 1 , - 1 ) , "foo foo (copy).txt txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo...txt" , 1 , - 1 ) , "foo.. (copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo..." , 1 , - 1 ) , "foo... (copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo. (copy)" , 1 , - 1 ) , "foo. (another copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (copy)" , 1 , - 1 ) , "foo (another copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (copy).txt" , 1 , - 1 ) , "foo (another copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (another copy)" , 1 , - 1 ) , "foo (3rd copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (another copy).txt" , 1 , - 1 ) , "foo (3rd copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo foo (another copy).txt" , 1 , - 1 ) , "foo foo (3rd copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (13th copy)" , 1 , - 1 ) , "foo (14th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (13th copy).txt" , 1 , - 1 ) , "foo (14th copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (21st copy)" , 1 , - 1 ) , "foo (22nd copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (21st copy).txt" , 1 , - 1 ) , "foo (22nd copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (22nd copy)" , 1 , - 1 ) , "foo (23rd copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (22nd copy).txt" , 1 , - 1 ) , "foo (23rd copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (23rd copy)" , 1 , - 1 ) , "foo (24th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (23rd copy).txt" , 1 , - 1 ) , "foo (24th copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (24th copy)" , 1 , - 1 ) , "foo (25th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (24th copy).txt" , 1 , - 1 ) , "foo (25th copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo foo (24th copy)" , 1 , - 1 ) , "foo foo (25th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo foo (24th copy).txt" , 1 , - 1 ) , "foo foo (25th copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo foo (100000000000000th copy).txt" , 1 , - 1 ) , "foo foo (copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (10th copy)" , 1 , - 1 ) , "foo (11th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (10th copy).txt" , 1 , - 1 ) , "foo (11th copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (11th copy)" , 1 , - 1 ) , "foo (12th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (11th copy).txt" , 1 , - 1 ) , "foo (12th copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (12th copy)" , 1 , - 1 ) , "foo (13th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (12th copy).txt" , 1 , - 1 ) , "foo (13th copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (110th copy)" , 1 , - 1 ) , "foo (111th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (110th copy).txt" , 1 , - 1 ) , "foo (111th copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (122nd copy)" , 1 , - 1 ) , "foo (123rd copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (122nd copy).txt" , 1 , - 1 ) , "foo (123rd copy).txt" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (123rd copy)" , 1 , - 1 ) , "foo (124th copy)" ) ;
 EEL_CHECK_STRING_RESULT ( get_duplicate_name ( "foo (123rd copy).txt" , 1 , - 1 ) , "foo (124th copy).txt" ) ;
 setlocale ( LC_MESSAGES , "" ) ;
 }