Query * inline_set_returning_function ( PlannerInfo * root , RangeTblEntry * rte ) {
 RangeTblFunction * rtfunc ;
 FuncExpr * fexpr ;
 Oid func_oid ;
 HeapTuple func_tuple ;
 Form_pg_proc funcform ;
 char * src ;
 Datum tmp ;
 bool isNull ;
 bool modifyTargetList ;
 MemoryContext oldcxt ;
 MemoryContext mycxt ;
 List * saveInvalItems ;
 inline_error_callback_arg callback_arg ;
 ErrorContextCallback sqlerrcontext ;
 SQLFunctionParseInfoPtr pinfo ;
 List * raw_parsetree_list ;
 List * querytree_list ;
 Query * querytree ;
 Assert ( rte -> rtekind == RTE_FUNCTION ) ;
 check_stack_depth ( ) ;
 if ( rte -> funcordinality ) return NULL ;
 if ( list_length ( rte -> functions ) != 1 ) return NULL ;
 rtfunc = ( RangeTblFunction * ) linitial ( rte -> functions ) ;
 if ( ! IsA ( rtfunc -> funcexpr , FuncExpr ) ) return NULL ;
 fexpr = ( FuncExpr * ) rtfunc -> funcexpr ;
 func_oid = fexpr -> funcid ;
 if ( ! fexpr -> funcretset ) return NULL ;
 if ( contain_volatile_functions ( ( Node * ) fexpr -> args ) || contain_subplans ( ( Node * ) fexpr -> args ) ) return NULL ;
 if ( pg_proc_aclcheck ( func_oid , GetUserId ( ) , ACL_EXECUTE ) != ACLCHECK_OK ) return NULL ;
 if ( FmgrHookIsNeeded ( func_oid ) ) return NULL ;
 func_tuple = SearchSysCache1 ( PROCOID , ObjectIdGetDatum ( func_oid ) ) ;
 if ( ! HeapTupleIsValid ( func_tuple ) ) elog ( ERROR , "cache lookup failed for function %u" , func_oid ) ;
 funcform = ( Form_pg_proc ) GETSTRUCT ( func_tuple ) ;
 if ( funcform -> prolang != SQLlanguageId || funcform -> proisstrict || funcform -> provolatile == PROVOLATILE_VOLATILE || funcform -> prosecdef || ! funcform -> proretset || ! heap_attisnull ( func_tuple , Anum_pg_proc_proconfig ) ) {
 ReleaseSysCache ( func_tuple ) ;
 return NULL ;
 }
 mycxt = AllocSetContextCreate ( CurrentMemoryContext , "inline_set_returning_function" , ALLOCSET_DEFAULT_MINSIZE , ALLOCSET_DEFAULT_INITSIZE , ALLOCSET_DEFAULT_MAXSIZE ) ;
 oldcxt = MemoryContextSwitchTo ( mycxt ) ;
 saveInvalItems = root -> glob -> invalItems ;
 root -> glob -> invalItems = NIL ;
 tmp = SysCacheGetAttr ( PROCOID , func_tuple , Anum_pg_proc_prosrc , & isNull ) ;
 if ( isNull ) elog ( ERROR , "null prosrc for function %u" , func_oid ) ;
 src = TextDatumGetCString ( tmp ) ;
 callback_arg . proname = NameStr ( funcform -> proname ) ;
 callback_arg . prosrc = src ;
 sqlerrcontext . callback = sql_inline_error_callback ;
 sqlerrcontext . arg = ( void * ) & callback_arg ;
 sqlerrcontext . previous = error_context_stack ;
 error_context_stack = & sqlerrcontext ;
 fexpr = ( FuncExpr * ) eval_const_expressions ( root , ( Node * ) fexpr ) ;
 if ( ! IsA ( fexpr , FuncExpr ) || fexpr -> funcid != func_oid ) goto fail ;
 if ( list_length ( fexpr -> args ) != funcform -> pronargs ) goto fail ;
 pinfo = prepare_sql_fn_parse_info ( func_tuple , ( Node * ) fexpr , fexpr -> inputcollid ) ;
 raw_parsetree_list = pg_parse_query ( src ) ;
 if ( list_length ( raw_parsetree_list ) != 1 ) goto fail ;
 querytree_list = pg_analyze_and_rewrite_params ( linitial ( raw_parsetree_list ) , src , ( ParserSetupHook ) sql_fn_parser_setup , pinfo ) ;
 if ( list_length ( querytree_list ) != 1 ) goto fail ;
 querytree = linitial ( querytree_list ) ;
 if ( ! IsA ( querytree , Query ) || querytree -> commandType != CMD_SELECT || querytree -> utilityStmt ) goto fail ;
 if ( ! check_sql_fn_retval ( func_oid , fexpr -> funcresulttype , querytree_list , & modifyTargetList , NULL ) && ( get_typtype ( fexpr -> funcresulttype ) == TYPTYPE_COMPOSITE || fexpr -> funcresulttype == RECORDOID ) ) goto fail ;
 if ( modifyTargetList ) goto fail ;
 if ( fexpr -> funcresulttype == RECORDOID && get_func_result_type ( func_oid , NULL , NULL ) == TYPEFUNC_RECORD && ! tlist_matches_coltypelist ( querytree -> targetList , rtfunc -> funccoltypes ) ) goto fail ;
 querytree = substitute_actual_srf_parameters ( querytree , funcform -> pronargs , fexpr -> args ) ;
 MemoryContextSwitchTo ( oldcxt ) ;
 querytree = copyObject ( querytree ) ;
 root -> glob -> invalItems = list_concat ( saveInvalItems , copyObject ( root -> glob -> invalItems ) ) ;
 MemoryContextDelete ( mycxt ) ;
 error_context_stack = sqlerrcontext . previous ;
 ReleaseSysCache ( func_tuple ) ;
 record_plan_function_dependency ( root , func_oid ) ;
 return querytree ;
 fail : MemoryContextSwitchTo ( oldcxt ) ;
 root -> glob -> invalItems = saveInvalItems ;
 MemoryContextDelete ( mycxt ) ;
 error_context_stack = sqlerrcontext . previous ;
 ReleaseSysCache ( func_tuple ) ;
 return NULL ;
 }