int ssl_verify_alarm_type ( long type ) {
 int al ;
 switch ( type ) {
 case X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT : case X509_V_ERR_UNABLE_TO_GET_CRL : case X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER : al = SSL_AD_UNKNOWN_CA ;
 break ;
 case X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE : case X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE : case X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY : case X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD : case X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD : case X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD : case X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD : case X509_V_ERR_CERT_NOT_YET_VALID : case X509_V_ERR_CRL_NOT_YET_VALID : case X509_V_ERR_CERT_UNTRUSTED : case X509_V_ERR_CERT_REJECTED : case X509_V_ERR_HOSTNAME_MISMATCH : case X509_V_ERR_EMAIL_MISMATCH : case X509_V_ERR_IP_ADDRESS_MISMATCH : case X509_V_ERR_DANE_NO_MATCH : case X509_V_ERR_EE_KEY_TOO_SMALL : case X509_V_ERR_CA_KEY_TOO_SMALL : case X509_V_ERR_CA_MD_TOO_WEAK : al = SSL_AD_BAD_CERTIFICATE ;
 break ;
 case X509_V_ERR_CERT_SIGNATURE_FAILURE : case X509_V_ERR_CRL_SIGNATURE_FAILURE : al = SSL_AD_DECRYPT_ERROR ;
 break ;
 case X509_V_ERR_CERT_HAS_EXPIRED : case X509_V_ERR_CRL_HAS_EXPIRED : al = SSL_AD_CERTIFICATE_EXPIRED ;
 break ;
 case X509_V_ERR_CERT_REVOKED : al = SSL_AD_CERTIFICATE_REVOKED ;
 break ;
 case X509_V_ERR_UNSPECIFIED : case X509_V_ERR_OUT_OF_MEM : case X509_V_ERR_INVALID_CALL : case X509_V_ERR_STORE_LOOKUP : al = SSL_AD_INTERNAL_ERROR ;
 break ;
 case X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT : case X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN : case X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY : case X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE : case X509_V_ERR_CERT_CHAIN_TOO_LONG : case X509_V_ERR_PATH_LENGTH_EXCEEDED : case X509_V_ERR_INVALID_CA : al = SSL_AD_UNKNOWN_CA ;
 break ;
 case X509_V_ERR_APPLICATION_VERIFICATION : al = SSL_AD_HANDSHAKE_FAILURE ;
 break ;
 case X509_V_ERR_INVALID_PURPOSE : al = SSL_AD_UNSUPPORTED_CERTIFICATE ;
 break ;
 default : al = SSL_AD_CERTIFICATE_UNKNOWN ;
 break ;
 }
 return ( al ) ;
 }