void chat_completion_deinit ( void ) {
 while ( global_lastmsgs != NULL ) last_msg_destroy ( & global_lastmsgs , global_lastmsgs -> data ) ;
 signal_remove ( "complete word" , ( SIGNAL_FUNC ) sig_complete_word ) ;
 signal_remove ( "complete command msg" , ( SIGNAL_FUNC ) sig_complete_msg ) ;
 signal_remove ( "complete command query" , ( SIGNAL_FUNC ) sig_complete_msg ) ;
 signal_remove ( "complete command action" , ( SIGNAL_FUNC ) sig_complete_msg ) ;
 signal_remove ( "complete erase command msg" , ( SIGNAL_FUNC ) sig_erase_complete_msg ) ;
 signal_remove ( "complete erase command query" , ( SIGNAL_FUNC ) sig_erase_complete_msg ) ;
 signal_remove ( "complete erase command action" , ( SIGNAL_FUNC ) sig_erase_complete_msg ) ;
 signal_remove ( "complete command connect" , ( SIGNAL_FUNC ) sig_complete_connect ) ;
 signal_remove ( "complete command server" , ( SIGNAL_FUNC ) sig_complete_connect ) ;
 signal_remove ( "complete command disconnect" , ( SIGNAL_FUNC ) sig_complete_tag ) ;
 signal_remove ( "complete command reconnect" , ( SIGNAL_FUNC ) sig_complete_tag ) ;
 signal_remove ( "complete command window server" , ( SIGNAL_FUNC ) sig_complete_tag ) ;
 signal_remove ( "complete command topic" , ( SIGNAL_FUNC ) sig_complete_topic ) ;
 signal_remove ( "complete command away" , ( SIGNAL_FUNC ) sig_complete_away ) ;
 signal_remove ( "complete command unalias" , ( SIGNAL_FUNC ) sig_complete_unalias ) ;
 signal_remove ( "complete command alias" , ( SIGNAL_FUNC ) sig_complete_alias ) ;
 signal_remove ( "complete command window goto" , ( SIGNAL_FUNC ) sig_complete_window ) ;
 signal_remove ( "complete command window item move" , ( SIGNAL_FUNC ) sig_complete_channel ) ;
 signal_remove ( "complete command server add" , ( SIGNAL_FUNC ) sig_complete_server ) ;
 signal_remove ( "complete command server remove" , ( SIGNAL_FUNC ) sig_complete_server ) ;
 signal_remove ( "complete command recode remove" , ( SIGNAL_FUNC ) sig_complete_target ) ;
 signal_remove ( "message public" , ( SIGNAL_FUNC ) sig_message_public ) ;
 signal_remove ( "message join" , ( SIGNAL_FUNC ) sig_message_join ) ;
 signal_remove ( "message private" , ( SIGNAL_FUNC ) sig_message_private ) ;
 signal_remove ( "message own_public" , ( SIGNAL_FUNC ) sig_message_own_public ) ;
 signal_remove ( "message own_private" , ( SIGNAL_FUNC ) sig_message_own_private ) ;
 signal_remove ( "nicklist remove" , ( SIGNAL_FUNC ) sig_nick_removed ) ;
 signal_remove ( "nicklist changed" , ( SIGNAL_FUNC ) sig_nick_changed ) ;
 signal_remove ( "send text" , ( SIGNAL_FUNC ) event_text ) ;
 signal_remove ( "server disconnected" , ( SIGNAL_FUNC ) sig_server_disconnected ) ;
 signal_remove ( "channel destroyed" , ( SIGNAL_FUNC ) sig_channel_destroyed ) ;
 signal_remove ( "setup changed" , ( SIGNAL_FUNC ) read_settings ) ;
 g_free_not_null ( completion_char ) ;
 g_free_not_null ( cmdchars ) ;
 }