PKCS8_PRIV_KEY_INFO * d2i_PKCS8_PRIV_KEY_INFO_bio ( BIO * bp , PKCS8_PRIV_KEY_INFO * * p8inf ) {
 return ASN1_d2i_bio_of ( PKCS8_PRIV_KEY_INFO , PKCS8_PRIV_KEY_INFO_new , d2i_PKCS8_PRIV_KEY_INFO , bp , p8inf ) ;
 }