TEST ( ExtensionCSPValidator , IsSecure ) {
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( std : : string ( ) , OPTIONS_ALLOW_UNSAFE_EVAL ) , "script-src 'self';
 object-src 'self';
" , MissingSecureSrcWarning ( "script-src" ) , MissingSecureSrcWarning ( "object-src" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "img-src https://google.com" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "img-src https://google.com;
 script-src 'self';
 object-src 'self';
" , MissingSecureSrcWarning ( "script-src" ) , MissingSecureSrcWarning ( "object-src" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src a b" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "script-src;
 object-src 'self';
" , InsecureValueWarning ( "script-src" , "a" ) , InsecureValueWarning ( "script-src" , "b" ) , MissingSecureSrcWarning ( "object-src" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src *" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src;
" , InsecureValueWarning ( "default-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self';
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'none';
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' ftp://google.com" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "ftp://google.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://google.com;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src *;
 default-src 'self'" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src;
 default-src 'self';
" , InsecureValueWarning ( "default-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self';
 default-src *;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
 default-src;
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self';
 default-src *;
 script-src *;
 script-src 'self'" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
 default-src;
 script-src;
 script-src 'self';
" , InsecureValueWarning ( "script-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self';
 default-src *;
 script-src 'self';
 script-src *;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
 default-src;
 script-src 'self';
 script-src;
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src *;
 script-src 'self'" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src;
 script-src 'self';
" , InsecureValueWarning ( "default-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src *;
 script-src 'self';
 img-src 'self'" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src;
 script-src 'self';
 img-src 'self';
" , InsecureValueWarning ( "default-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src *;
 script-src 'self';
 object-src 'self';
" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src;
 script-src 'self';
 object-src 'self';
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src 'self';
 object-src 'self';
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'unsafe-eval';
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'unsafe-eval'" , OPTIONS_NONE ) , "default-src;
" , InsecureValueWarning ( "default-src" , "'unsafe-eval'" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'unsafe-inline'" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src;
" , InsecureValueWarning ( "default-src" , "'unsafe-inline'" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'unsafe-inline' 'none'" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'none';
" , InsecureValueWarning ( "default-src" , "'unsafe-inline'" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http://google.com" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "http://google.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://google.com;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' chrome://resources;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' chrome-extension://aabbcc;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' chrome-extension-resource://aabbcc;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https:" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https:" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http:" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "http:" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' google.com" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "google.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' *" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' *:*" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "*:*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' *:*/" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "*:*/" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' *:*/path" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "*:*/path" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*:*" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://*:*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*:*/" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://*:*/" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*:*/path" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://*:*/path" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.com" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://*.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.*.google.com/" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://*.*.google.com/" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.*.google.com:*/" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://*.*.google.com:*/" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://www.*.google.com/" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://www.*.google.com/" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://www.*.google.com:*/" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "https://www.*.google.com:*/" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' chrome://*" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "chrome://*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' chrome-extension://*" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "chrome-extension://*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' chrome-extension://" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "chrome-extension://" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.google.com;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.google.com:1;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.google.com:*;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.google.com:1/;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.google.com:*/;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http://127.0.0.1;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http://localhost;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http://lOcAlHoSt;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self' http://lOcAlHoSt;
" ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http://127.0.0.1:9999;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http://localhost:8888;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http://127.0.0.1.example.com" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "http://127.0.0.1.example.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' http://localhost.example.com" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "http://localhost.example.com" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' blob:;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' blob:http://example.com/XXX" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "blob:http://example.com/XXX" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' filesystem:;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' filesystem:http://example.com/XX" , OPTIONS_ALLOW_UNSAFE_EVAL ) , "default-src 'self';
" , InsecureValueWarning ( "default-src" , "filesystem:http://example.com/XX" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://*.googleapis.com;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src 'self' https://x.googleapis.com;
" , OPTIONS_ALLOW_UNSAFE_EVAL ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src 'self';
 object-src *" , OPTIONS_NONE ) , "script-src 'self';
 object-src;
" , InsecureValueWarning ( "object-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src 'self';
 object-src *" , OPTIONS_ALLOW_INSECURE_OBJECT_SRC ) , "script-src 'self';
 object-src;
" , InsecureValueWarning ( "object-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src 'self';
 object-src *;
 plugin-types application/pdf;
" , OPTIONS_ALLOW_INSECURE_OBJECT_SRC ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src 'self';
 object-src *;
 " "plugin-types application/x-shockwave-flash" , OPTIONS_ALLOW_INSECURE_OBJECT_SRC ) , "script-src 'self';
 object-src;
 " "plugin-types application/x-shockwave-flash;
" , InsecureValueWarning ( "object-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src 'self';
 object-src *;
 " "plugin-types application/x-shockwave-flash application/pdf;
" , OPTIONS_ALLOW_INSECURE_OBJECT_SRC ) , "script-src 'self';
 object-src;
 " "plugin-types application/x-shockwave-flash application/pdf;
" , InsecureValueWarning ( "object-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src 'self';
 object-src http://www.example.com;
 " "plugin-types application/pdf;
" , OPTIONS_ALLOW_INSECURE_OBJECT_SRC ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "object-src http://www.example.com blob:;
 script-src 'self';
 " "plugin-types application/pdf;
" , OPTIONS_ALLOW_INSECURE_OBJECT_SRC ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src 'self';
 object-src http://*.example.com;
 " "plugin-types application/pdf;
" , OPTIONS_ALLOW_INSECURE_OBJECT_SRC ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "script-src *;
 object-src *;
 plugin-types application/pdf;
" , OPTIONS_ALLOW_INSECURE_OBJECT_SRC ) , "script-src;
 object-src *;
 plugin-types application/pdf;
" , InsecureValueWarning ( "script-src" , "*" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src;
 script-src" " 'sha256-hndjYvzUzy2Ykuad81Cwsl1FOXX/qYs/aDVyUyNZwBw='" " 'sha384-bSVm1i3sjPBRM4TwZtYTDjk9JxZMExYHWbFmP1SxDhJH4ue0Wu9OPOkY5hcqRcS" "t'" " 'sha512-440MmBLtj9Kp5Bqloogn9BqGDylY8vFsv5/zXL1zH2fJVssCoskRig4gyM+9Kqw" "vCSapSz5CVoUGHQcxv43UQg==';
" , OPTIONS_NONE ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src;
 script-src 'sha1-eYyYGmKWdhpUewohaXk9o8IaLSw=';
" , OPTIONS_NONE ) , "default-src;
 script-src;
" , InsecureValueWarning ( "script-src" , "'sha1-eYyYGmKWdhpUewohaXk9o8IaLSw='" ) ) ) ;
 EXPECT_TRUE ( CheckCSP ( SanitizeCSP ( "default-src;
 script-src 'sha256-hndjYvzUzy2Ykuad81Cwsl1FOXX/qYs/aDVyUyNZ" "wBw= sha256-qznLcsROx4GACP2dm0UCKCzCG+HiZ1guq6ZZDob/Tng=';
" , OPTIONS_NONE ) , "default-src;
 script-src;
" , InsecureValueWarning ( "script-src" , "'sha256-hndjYvzUzy2Ykuad81Cwsl1FOXX/qYs/aDVyUyNZwBw=" ) , InsecureValueWarning ( "script-src" , "sha256-qznLcsROx4GACP2dm0UCKCzCG+HiZ1guq6ZZDob/Tng='" ) ) ) ;
 }