IN_PROC_BROWSER_TEST_F ( AppApiTest , DISABLED_AppProcess ) {
 LOG ( INFO ) << "Start of test." ;
 extensions : : ProcessMap * process_map = extensions : : ProcessMap : : Get ( browser ( ) -> profile ( ) ) ;
 ASSERT_TRUE ( LoadExtension ( test_data_dir_ . AppendASCII ( "app_process" ) ) ) ;
 LOG ( INFO ) << "Loaded extension." ;
 GURL base_url = GetTestBaseURL ( "app_process" ) ;
 ui_test_utils : : NavigateToURLWithDisposition ( browser ( ) , base_url . Resolve ( "path1/empty.html" ) , WindowOpenDisposition : : NEW_FOREGROUND_TAB , ui_test_utils : : BROWSER_TEST_WAIT_FOR_NAVIGATION ) ;
 EXPECT_TRUE ( process_map -> Contains ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 1 ) -> GetRenderProcessHost ( ) -> GetID ( ) ) ) ;
 EXPECT_FALSE ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 1 ) -> GetWebUI ( ) ) ;
 LOG ( INFO ) << "Nav 1." ;
 ui_test_utils : : NavigateToURLWithDisposition ( browser ( ) , base_url . Resolve ( "path2/empty.html" ) , WindowOpenDisposition : : NEW_FOREGROUND_TAB , ui_test_utils : : BROWSER_TEST_WAIT_FOR_NAVIGATION ) ;
 EXPECT_TRUE ( process_map -> Contains ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 2 ) -> GetRenderProcessHost ( ) -> GetID ( ) ) ) ;
 EXPECT_FALSE ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 2 ) -> GetWebUI ( ) ) ;
 LOG ( INFO ) << "Nav 2." ;
 content : : WindowedNotificationObserver tab_added_observer ( chrome : : NOTIFICATION_TAB_ADDED , content : : NotificationService : : AllSources ( ) ) ;
 chrome : : NewTab ( browser ( ) ) ;
 tab_added_observer . Wait ( ) ;
 LOG ( INFO ) << "New tab." ;
 ui_test_utils : : NavigateToURL ( browser ( ) , base_url . Resolve ( "path3/empty.html" ) ) ;
 LOG ( INFO ) << "Nav 3." ;
 EXPECT_FALSE ( process_map -> Contains ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 3 ) -> GetRenderProcessHost ( ) -> GetID ( ) ) ) ;
 EXPECT_FALSE ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 3 ) -> GetWebUI ( ) ) ;
 ASSERT_EQ ( 4 , browser ( ) -> tab_strip_model ( ) -> count ( ) ) ;
 WebContents * tab = browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 1 ) ;
 EXPECT_EQ ( tab -> GetRenderProcessHost ( ) , browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 2 ) -> GetRenderProcessHost ( ) ) ;
 EXPECT_NE ( tab -> GetRenderProcessHost ( ) , browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 3 ) -> GetRenderProcessHost ( ) ) ;
 ASSERT_EQ ( 1u , chrome : : GetBrowserCount ( browser ( ) -> profile ( ) ) ) ;
 OpenWindow ( tab , base_url . Resolve ( "path1/empty.html" ) , true , NULL ) ;
 LOG ( INFO ) << "WindowOpenHelper 1." ;
 OpenWindow ( tab , base_url . Resolve ( "path2/empty.html" ) , true , NULL ) ;
 LOG ( INFO ) << "WindowOpenHelper 2." ;
 OpenWindow ( tab , base_url . Resolve ( "path3/empty.html" ) , true , NULL ) ;
 LOG ( INFO ) << "WindowOpenHelper 3." ;
 const GURL & app_url ( base_url . Resolve ( "path1/empty.html" ) ) ;
 const GURL & non_app_url ( base_url . Resolve ( "path3/empty.html" ) ) ;
 NavigateInRenderer ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 2 ) , non_app_url ) ;
 LOG ( INFO ) << "NavigateTabHelper 1." ;
 NavigateInRenderer ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 3 ) , app_url ) ;
 LOG ( INFO ) << "NavigateTabHelper 2." ;
 EXPECT_NE ( tab -> GetRenderProcessHost ( ) , browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 2 ) -> GetRenderProcessHost ( ) ) ;
 EXPECT_EQ ( tab -> GetRenderProcessHost ( ) , browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 3 ) -> GetRenderProcessHost ( ) ) ;
 NavigateInRenderer ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 6 ) , app_url ) ;
 LOG ( INFO ) << "NavigateTabHelper 3." ;
 EXPECT_EQ ( tab -> GetRenderProcessHost ( ) , browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 6 ) -> GetRenderProcessHost ( ) ) ;
 bool windowOpenerValid = false ;
 ASSERT_TRUE ( content : : ExecuteScriptAndExtractBool ( browser ( ) -> tab_strip_model ( ) -> GetWebContentsAt ( 6 ) , "window.domAutomationController.send(window.opener != null)" , & windowOpenerValid ) ) ;
 ASSERT_TRUE ( windowOpenerValid ) ;
 LOG ( INFO ) << "End of test." ;
 }