static PHP_MINIT_FUNCTION ( zip ) {

 memcpy ( & zip_object_handlers , zend_get_std_object_handlers ( ) , sizeof ( zend_object_handlers ) ) ;
 zip_object_handlers . clone_obj = NULL ;
 zip_object_handlers . get_property_ptr_ptr = php_zip_get_property_ptr_ptr ;
 zip_object_handlers . get_properties = php_zip_get_properties ;
 zip_object_handlers . read_property = php_zip_read_property ;
 zip_object_handlers . has_property = php_zip_has_property ;
 INIT_CLASS_ENTRY ( ce , "ZipArchive" , zip_class_functions ) ;
 ce . create_object = php_zip_object_new ;
 zip_class_entry = zend_register_internal_class ( & ce TSRMLS_CC ) ;
 zend_hash_init ( & zip_prop_handlers , 0 , NULL , NULL , 1 ) ;
 php_zip_register_prop_handler ( & zip_prop_handlers , "status" , php_zip_status , NULL , NULL , IS_LONG TSRMLS_CC ) ;
 php_zip_register_prop_handler ( & zip_prop_handlers , "statusSys" , php_zip_status_sys , NULL , NULL , IS_LONG TSRMLS_CC ) ;
 php_zip_register_prop_handler ( & zip_prop_handlers , "numFiles" , php_zip_get_num_files , NULL , NULL , IS_LONG TSRMLS_CC ) ;
 php_zip_register_prop_handler ( & zip_prop_handlers , "filename" , NULL , NULL , php_zipobj_get_filename , IS_STRING TSRMLS_CC ) ;
 php_zip_register_prop_handler ( & zip_prop_handlers , "comment" , NULL , php_zipobj_get_zip_comment , NULL , IS_STRING TSRMLS_CC ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CREATE" , ZIP_CREATE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "EXCL" , ZIP_EXCL ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CHECKCONS" , ZIP_CHECKCONS ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "OVERWRITE" , ZIP_OVERWRITE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "FL_NOCASE" , ZIP_FL_NOCASE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "FL_NODIR" , ZIP_FL_NODIR ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "FL_COMPRESSED" , ZIP_FL_COMPRESSED ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "FL_UNCHANGED" , ZIP_FL_UNCHANGED ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_DEFAULT" , ZIP_CM_DEFAULT ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_STORE" , ZIP_CM_STORE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_SHRINK" , ZIP_CM_SHRINK ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_REDUCE_1" , ZIP_CM_REDUCE_1 ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_REDUCE_2" , ZIP_CM_REDUCE_2 ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_REDUCE_3" , ZIP_CM_REDUCE_3 ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_REDUCE_4" , ZIP_CM_REDUCE_4 ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_IMPLODE" , ZIP_CM_IMPLODE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_DEFLATE" , ZIP_CM_DEFLATE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_DEFLATE64" , ZIP_CM_DEFLATE64 ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_PKWARE_IMPLODE" , ZIP_CM_PKWARE_IMPLODE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_BZIP2" , ZIP_CM_BZIP2 ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_LZMA" , ZIP_CM_LZMA ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_TERSE" , ZIP_CM_TERSE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_LZ77" , ZIP_CM_LZ77 ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_WAVPACK" , ZIP_CM_WAVPACK ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "CM_PPMD" , ZIP_CM_PPMD ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_OK" , ZIP_ER_OK ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_MULTIDISK" , ZIP_ER_MULTIDISK ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_RENAME" , ZIP_ER_RENAME ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_CLOSE" , ZIP_ER_CLOSE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_SEEK" , ZIP_ER_SEEK ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_READ" , ZIP_ER_READ ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_WRITE" , ZIP_ER_WRITE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_CRC" , ZIP_ER_CRC ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_ZIPCLOSED" , ZIP_ER_ZIPCLOSED ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_NOENT" , ZIP_ER_NOENT ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_EXISTS" , ZIP_ER_EXISTS ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_OPEN" , ZIP_ER_OPEN ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_TMPOPEN" , ZIP_ER_TMPOPEN ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_ZLIB" , ZIP_ER_ZLIB ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_MEMORY" , ZIP_ER_MEMORY ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_CHANGED" , ZIP_ER_CHANGED ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_COMPNOTSUPP" , ZIP_ER_COMPNOTSUPP ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_EOF" , ZIP_ER_EOF ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_INVAL" , ZIP_ER_INVAL ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_NOZIP" , ZIP_ER_NOZIP ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_INTERNAL" , ZIP_ER_INTERNAL ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_INCONS" , ZIP_ER_INCONS ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_REMOVE" , ZIP_ER_REMOVE ) ;
 REGISTER_ZIP_CLASS_CONST_LONG ( "ER_DELETED" , ZIP_ER_DELETED ) ;
 php_register_url_stream_wrapper ( "zip" , & php_stream_zip_wrapper TSRMLS_CC ) ;

 le_zip_entry = zend_register_list_destructors_ex ( php_zip_free_entry , NULL , le_zip_entry_name , module_number ) ;
 return SUCCESS ;
 }